const $=id=>document.getElementById(id);let peer=null,room="",name="",pfp="",connections=new Map(),transfers=new Map(),screenStream=null;const CHUNK=48*1024;
const clean=s=>String(s||"").trim().replace(/[^a-zA-Z0-9_-]/g,"-").slice(0,40),formatSize=n=>n<1024?n+" B":n<1048576?(n/1024).toFixed(1)+" KB":n<1073741824?(n/1048576).toFixed(1)+" MB":(n/1073741824).toFixed(1)+" GB";
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),1800)}
function setStatus(){let n=connections.size;$("status").textContent=n?"Connected":"Waiting for peers"}
function scroll(){let b=$("messages");b.scrollTop=b.scrollHeight}
function avatarHtml(d,mine){let src=mine?pfp:(d.pfp||"");return src?'<img src="'+src.replace(/"/g,"&quot;")+'">':(mine?(name||"G").charAt(0):(d.name||"G").charAt(0))}
function renderFile(f){
 let card=document.createElement("div");card.className="fileCard";let url=URL.createObjectURL(f.blob);
 if(f.type.startsWith("image/")){let x=document.createElement("img");x.src=url;x.alt=f.name;card.append(x)}
 else if(f.type.startsWith("video/")){let x=document.createElement("video");x.src=url;x.controls=true;x.playsInline=true;card.append(x)}
 let meta=document.createElement("div");meta.className="fileMeta";let icon=document.createElement("div");icon.className="fileIcon";icon.textContent=f.type.startsWith("image/")?"🖼️":f.type.startsWith("video/")?"🎬":"📎";let info=document.createElement("div");info.className="fileInfo";let nm=document.createElement("div");nm.className="fileName";nm.textContent=f.name;let sz=document.createElement("div");sz.className="fileSize";sz.textContent=formatSize(f.size);info.append(nm,sz);let dl=document.createElement("a");dl.className="download";dl.textContent="Save";dl.href=url;dl.download=f.name;meta.append(icon,info,dl);card.append(meta);return card
}
function addMessage(d,mine=false){
 let box=$("messages"),empty=box.querySelector(".empty");if(empty)empty.remove();let el=document.createElement("div");el.className="msg"+(mine?" mine":"");let av=document.createElement("div");av.className="avatar";av.innerHTML=avatarHtml(d,mine);let wrap=document.createElement("div");wrap.className="bubbleWrap";let n=document.createElement("div");n.className="name";n.textContent=mine?"You":d.name||"Guest";wrap.append(n);let bubble=document.createElement("div");bubble.className="bubble";if(d.text){let t=document.createElement("div");t.className="text";t.textContent=d.text;bubble.append(t)}if(d.file)bubble.append(renderFile(d.file));wrap.append(bubble);el.append(av,wrap);box.append(el);scroll()
}
function broadcast(d,except){for(let [id,c] of connections)if(id!==except&&c.open)try{c.send(d)}catch(e){}}
function receiveChunk(d,from){
 let t=transfers.get(d.id);if(!t){t={name:d.name,size:d.size,type:d.mime,chunks:[],received:0,total:d.total};transfers.set(d.id,t)}
 t.chunks[d.index]=d.chunk;t.received++;broadcast(d,from);
 if(d.end){let blob=new Blob(t.chunks,{type:t.type||"application/octet-stream"});transfers.delete(d.id);addMessage({name:d.sender||"Guest",pfp:d.pfp||"",file:{name:t.name,size:t.size,type:t.type,blob}},false)}
}
async function sendFile(file){
 if(!connections.size){toast("Connect to a peer first");return}
 let id=name+"-"+Date.now()+"-"+Math.random().toString(36).slice(2),total=Math.ceil(file.size/CHUNK)||1;addMessage({file:{name:file.name,size:file.size,type:file.type,blob:file}},true);
 let msg=$("messages").lastElementChild,bar=document.createElement("div");bar.className="progress";let i=document.createElement("i");bar.append(i);msg.querySelector(".fileCard").append(bar);
 for(let n=0;n<total;n++){let chunk=await file.slice(n*CHUNK,(n+1)*CHUNK).arrayBuffer();broadcast({type:"file",id,name:file.name,size:file.size,mime:file.type,total,index:n,chunk,sender:name,pfp,end:n===total-1});i.style.width=((n+1)/total*100)+"%";await new Promise(r=>setTimeout(r,0))}setTimeout(()=>bar.remove(),500)
}
function attach(c){
 connections.set(c.peer,c);setStatus();c.on("open",()=>{setStatus();try{c.send({type:"hello",name,pfp})}catch(e){}});c.on("data",d=>{if(d.type==="hello"){if(d.name)addMessage({name:d.name,pfp:d.pfp,text:"joined the room"});return}if(d.type==="chat"){addMessage(d);broadcast(d,c.peer);return}if(d.type==="file"){receiveChunk(d,c.peer)}});c.on("close",()=>{connections.delete(c.peer);setStatus()});c.on("error",()=>{connections.delete(c.peer);setStatus()})
}
function connectTo(id){if(!peer||id===peer.id||connections.has(id))return;attach(peer.connect(id,{reliable:true}))}
function start(){
 room=clean($("room").value)||Math.random().toString(36).slice(2,8);name=($("name").value.trim()||"Guest").slice(0,30);$("roomDisplay").value=room;$("join").classList.add("hidden");$("app").classList.remove("hidden");$("myAvatar").innerHTML=pfp?'<img src="'+pfp.replace(/"/g,"&quot;")+'" style="width:100%;height:100%;object-fit:cover;border-radius:12px">':"✦";
 const roomHash=(()=>{let h=2166136261;for(let i=0;i<room.length;i++){h^=room.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)})(),prefix="p2p-chat-"+roomHash+"-",slots=Array.from({length:12},(_,i)=>prefix+i),tried=new Set();
 function trySlot(){const available=slots.filter(x=>!tried.has(x));if(!available.length){toast("Room is full");return}const id=available[Math.floor(Math.random()*available.length)];tried.add(id);peer=new Peer(id,{host:"0.peerjs.com",port:443,path:"/",secure:true});peer.on("open",myId=>{setStatus();slots.filter(x=>x!==myId).forEach(connectTo);localStorage.setItem("p2p-last-room",room)});peer.on("connection",attach);peer.on("call",call=>{call.answer();call.on("error",()=>{});call.on("stream",stream=>{let box=$("messages"),empty=box.querySelector(".empty");if(empty)empty.remove();let el=document.createElement("div");el.className="msg";let av=document.createElement("div");av.className="avatar";let wrap=document.createElement("div");wrap.className="bubbleWrap";let n=document.createElement("div");n.className="name";n.textContent=(call.metadata&&call.metadata.name)||"Guest";wrap.append(n);let bubble=document.createElement("div");bubble.className="bubble";let t=document.createElement("div");t.className="text";t.textContent="Live screen share";bubble.append(t);let v=document.createElement("video");v.srcObject=stream;v.autoplay=true;v.playsInline=true;v.controls=true;v.style.cssText="display:block;width:100%;max-height:390px;object-fit:contain;background:#050608;border-radius:10px";bubble.append(v);wrap.append(bubble);el.append(av,wrap);box.append(el);scroll()})});peer.on("error",e=>{if(e.type==="unavailable-id"){trySlot();return}toast("Connection error: "+e.type);$("status").textContent="Connection error"})}trySlot()
}
$("pfpPick").onclick=()=>$("pfpInput").click();$("pfpInput").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{pfp=r.result;$("pfpPreview").innerHTML='<img src="'+pfp+'" style="width:100%;height:100%;object-fit:cover">';localStorage.setItem("chat2-pfp",pfp)};r.readAsDataURL(f)};
$("name").value=localStorage.getItem("chat2-name")||"";pfp=localStorage.getItem("chat2-pfp")||"";if(pfp)$("pfpPreview").innerHTML='<img src="'+pfp+'" style="width:100%;height:100%;object-fit:cover">';
$("joinBtn").onclick=()=>{localStorage.setItem("chat2-name",$("name").value.trim());start()};$("room").addEventListener("keydown",e=>{if(e.key==="Enter"){$("joinBtn").click()}});
$("send").onsubmit=e=>{e.preventDefault();let text=$("message").value.trim();if(!text)return;let d={type:"chat",name,pfp,text,time:Date.now()};addMessage(d,true);broadcast(d);$("message").value="";$("message").focus()};
$("attachBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>{[...e.target.files].forEach(sendFile);e.target.value=""};
$("shareBtn").onclick=async()=>{if(screenStream){screenStream.getTracks().forEach(t=>t.stop());screenStream=null;$("shareBtn").textContent="Share screen + audio";return}try{screenStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});$("shareBtn").textContent="Stop sharing";screenStream.getVideoTracks()[0].onended=()=>{screenStream=null;$("shareBtn").textContent="Share screen + audio"};for(let [id,c] of connections)if(c.open){try{const call=peer.call(id,screenStream,{metadata:{name,pfp}});call.on("error",()=>toast("Screen share connection failed"))}catch(e){toast("Could not share with a peer")}}}catch(e){toast("Screen sharing cancelled")}};
async function saveChat(){toast("Preparing chat...");const clone=$("messages").cloneNode(true);clone.querySelectorAll(".progress").forEach(x=>x.remove());const media=clone.querySelectorAll("img,video");for(const el of media){if(el.tagName==="VIDEO"&&el.srcObject){const wrap=document.createElement("div");wrap.className="savedVideo";wrap.innerHTML="<div class=\\"videoIcon\\">▶</div><div><b>Live screen share</b><div>Live screen sharing cannot be stored after the chat ends.</div></div>";el.replaceWith(wrap);continue}const src=el.getAttribute("src");if(src&&src.startsWith("blob:")){try{const res=await fetch(src);const blob=await res.blob();const data=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(blob)});el.setAttribute("src",data)}catch(e){}}}const css=document.querySelector("link[rel=\\"stylesheet\\"]")?await fetch(document.querySelector("link[rel=\\"stylesheet\\"]").href).then(r=>r.text()).catch(()=>""):document.querySelector("style")?.textContent||"";const safeRoom=room.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Chat - '+safeRoom+'</title><style>'+css+'body{overflow:auto;background:#07080c}.saved{width:100%;max-width:1000px;margin:0 auto;min-height:100vh}.savedHead{padding:22px 18px;border-bottom:1px solid var(--line);background:#0b0e14}.savedHead h1{margin:0;font-size:20px}.savedHead p{margin:5px 0 0;color:var(--muted);font-size:12px}.messages{height:auto;overflow:visible}.savedVideo{min-height:180px;display:flex;align-items:center;gap:14px;padding:20px;background:#090c12;border-radius:10px;color:#fff}.videoIcon{width:48px;height:48px;border-radius:50%;display:grid;place-items:center;background:#6658ee;font-size:20px}.savedNote{padding:18px;color:var(--muted);font-size:12px;border-top:1px solid var(--line)}</style></head><body><div class="saved"><div class="savedHead"><h1>Chat App 2</h1><p>Room: '+safeRoom+' · Saved chat</p></div>'+clone.outerHTML+'<div class="savedNote">This is a saved copy of the chat. Images and videos from the chat are embedded inside this HTML file.</div></div></body></html>';const blob=new Blob([html],{type:"text/html;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="chat-"+(room||"saved")+"-"+new Date().toISOString().slice(0,10)+".html";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Chat saved with media")}
async function copyRoom(){try{await navigator.clipboard.writeText(room);toast("Room code copied")}catch(e){toast(room)}}$("saveBtn").onclick=saveChat;$("copyBtn").onclick=copyRoom;$("copyRoomBtn").onclick=copyRoom;$("leaveBtn").onclick=()=>location.reload();
