import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import*as Y from"yjs";
import{WebrtcProvider}from"y-webrtc";
import Message from"./Message.jsx";

const defaults={showTyping:true,chatSize:"normal",ttsEnabled:true,ttsVoice:"",ttsRate:1,ttsPitch:1,sttLanguage:"en-US",showScreens:true};
const themes={light:{bgColor:"#f4f5fa",chatBg:"#fff",textColor:"#20243a",headerBg:"#5548cf",headerText:"#fff",messageBg:"#f1f2f8",messageOwnBg:"#5548cf",messageOwnText:"#fff",borderColor:"#e4e6ef",inputBg:"#fff",linkColor:"#5548cf"},dark:{bgColor:"#171923",chatBg:"#222532",textColor:"#e8eaf2",headerBg:"#2b2e3b",headerText:"#fff",messageBg:"#303443",messageOwnBg:"#665bd7",messageOwnText:"#fff",borderColor:"#393d4d",inputBg:"#2a2e3c",linkColor:"#b9b2ff"},full:{bgColor:"#0a0b10",chatBg:"#15161d",textColor:"#f1f1f5",headerBg:"#1e1f28",headerText:"#fff",messageBg:"#24252e",messageOwnBg:"#4941aa",messageOwnText:"#fff",borderColor:"#2d2e38",inputBg:"#1b1c24",linkColor:"#c4beff"}};
const load=(k,d)=>{try{return Object.assign({},d,JSON.parse(localStorage.getItem(k)||"{}"))}catch{return Object.assign({},d)}};
const rid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const clean=s=>String(s||"").trim().toLowerCase().replace(/[^a-z0-9_-]/g,"-").slice(0,80);
const dataFile=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});
const avatar=n=>"https://api.dicebear.com/9.x/initials/svg?seed="+encodeURIComponent(n);

function setTheme(t,custom){
const s=t==="custom"?custom:themes[t]||themes.light;
const r=document.documentElement;
Object.entries(s).forEach(([k,v])=>r.style.setProperty("--custom-"+k,v));
r.dataset.theme=t;
document.body.style.backgroundImage=s.backgroundImage?"url("+s.backgroundImage+")":"";
document.body.classList.toggle("custom-background",!!s.backgroundImage);
localStorage.setItem("chatTheme",t);
if(t==="custom")localStorage.setItem("customTheme",JSON.stringify(s));
}

function App(){
const[nickname,setNickname]=useState(localStorage.getItem("chatNickname")||"");
const[code,setCode]=useState("");
const[theme,setThemeState]=useState(localStorage.getItem("chatTheme")||"light");
const[custom,setCustom]=useState(load("customTheme",themes.light));
const[settings,setSettings]=useState(load("chatSettings",defaults));
const[room,setRoom]=useState(null),[items,setItems]=useState([]),[text,setText]=useState(""),[typing,setTyping]=useState([]);
const[editing,setEditing]=useState(null),[tab,setTab]=useState("chat"),[showSettings,setShowSettings]=useState(false),[showCustom,setShowCustom]=useState(false),[poll,setPoll]=useState(false),[recording,setRecording]=useState(false),[videoRecording,setVideoRecording]=useState(false),[screen,setScreen]=useState(null),[online,setOnline]=useState(0),[toast,setToast]=useState("");
const map=useRef(null),provider=useRef(null),awareness=useRef(null),timer=useRef(null),rec=useRef(null),chunks=useRef([]),screenVideo=useRef(null);

useEffect(()=>{setTheme(theme,custom)},[]);
useEffect(()=>()=>{provider.current?.destroy();},[]);
useEffect(()=>{if(!room)return;const m=room.map;map.current=m;const refresh=()=>setItems(Object.values(m.toJSON()).sort((a,b)=>(a.time||0)-(b.time||0)));refresh();m.observe(refresh);const a=room.provider.awareness;awareness.current=a;const update=()=>{const states=[...a.getStates().values()];setOnline(states.length);setTyping(states.map(s=>s&&s.typing?s.name:"").filter(n=>n&&n!==nickname))};a.on("change",update);update();return()=>{m.unobserve(refresh);a.off("change",update)}},[room,nickname]);
useEffect(()=>{if(screenVideo.current)screenVideo.current.srcObject=screen||null},[screen]);

const join=e=>{e.preventDefault();const c=clean(code),n=nickname.trim();if(!c||!n)return;localStorage.setItem("chatNickname",n);const d=new Y.Doc();const p=new WebrtcProvider("chat-app2-"+c,d,{password:c,filterBcConns:false});const m=d.getMap("messages");p.awareness.setLocalStateField("name",n);p.awareness.setLocalStateField("typing",false);provider.current=p;setRoom({code:c,map:m,provider:p})};
const leave=()=>{provider.current?.destroy();provider.current=null;map.current=null;setRoom(null);setItems([]);setTab("chat")};
const send=extra=>{const value=text.trim();if(!value&&!extra?.file&&!extra?.poll)return;const m=Object.assign({id:rid(),username:nickname,nickname,avatar:avatar(nickname),text:value,time:Date.now()},extra||{});map.current?.set(m.id,m);setText("");awareness.current?.setLocalStateField("typing",false)};
const typingChange=e=>{setText(e.target.value);if(settings.showTyping){awareness.current?.setLocalStateField("typing",true);clearTimeout(timer.current);timer.current=setTimeout(()=>awareness.current?.setLocalStateField("typing",false),1000)}};
const format=t=>t.split(/(https?:\/\/[^\s]+)/g).map((p,i)=>/^https?:\/\//.test(p)?<a key={i} href={p} target="_blank" rel="noreferrer">{p}</a>:p);
const updateSetting=(k,v)=>{const s=Object.assign({},settings,{[k]:v});setSettings(s);localStorage.setItem("chatSettings",JSON.stringify(s))};
const updateCustom=(k,v)=>{const s=Object.assign({},custom,{[k]:v});setCustom(s);setThemeState("custom");setTheme("custom",s)};
const edit=(id,v)=>{const m=map.current?.get(id);if(m){map.current.set(id,Object.assign({},m,{text:v,edited:true}))}setEditing(null)};
const vote=(id,i)=>{const m=map.current?.get(id);if(!m?.poll)return;const p=JSON.parse(JSON.stringify(m.poll));Object.keys(p.votes||{}).forEach(k=>p.votes[k]=(p.votes[k]||[]).filter(n=>n!==nickname));p.votes[i]=(p.votes[i]||[]).concat(nickname);map.current.set(id,Object.assign({},m,{poll:p}))};
const speak=t=>{if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=Number(settings.ttsRate)||1;u.pitch=Number(settings.ttsPitch)||1;const v=window.speechSynthesis.getVoices().find(x=>x.name===settings.ttsVoice);if(v)u.voice=v;window.speechSynthesis.speak(u)};
const speech=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){setToast("Speech recognition is not supported");return}const r=new R();r.lang=settings.sttLanguage;r.onresult=e=>setText(v=>v+" "+e.results[0][0].transcript);r.start()};
const attach=async e=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;if(f.size>8*1024*1024){setToast("Maximum file size is 8 MB");return}send({file:await dataFile(f),fileName:f.name,fileType:f.type})};
const recordAudio=async()=>{if(recording){rec.current?.stop();return}try{const s=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(s);chunks.current=[];r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=async()=>{s.getTracks().forEach(t=>t.stop());const b=new Blob(chunks.current,{type:r.mimeType||"audio/webm"});if(b.size<=8*1024*1024)send({file:await dataFile(new File([b],"voice.webm",{type:b.type})),fileName:"voice.webm",fileType:b.type});setRecording(false)};rec.current=r;r.start();setRecording(true)}catch{setToast("Microphone permission denied")}};
const recordVideo=async()=>{if(videoRecording){rec.current?.stop();return}try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});const r=new MediaRecorder(s);chunks.current=[];r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=async()=>{s.getTracks().forEach(t=>t.stop());const b=new Blob(chunks.current,{type:r.mimeType||"video/webm"});if(b.size<=8*1024*1024)send({file:await dataFile(new File([b],"video.webm",{type:b.type})),fileName:"video.webm",fileType:b.type});setVideoRecording(false)};rec.current=r;r.start();setVideoRecording(true)}catch{setToast("Camera or microphone permission denied")}};
const share=async()=>{if(screen){screen.getTracks().forEach(t=>t.stop());setScreen(null);return}try{const s=await navigator.mediaDevices.getDisplayMedia({video:true});s.getVideoTracks()[0].onended=()=>setScreen(null);setScreen(s)}catch{}};
const makePoll=()=>{const opts=window.__pollOptions?.map(x=>x.trim()).filter(Boolean)||[];if(!window.__pollTitle?.trim()||opts.length<2)return;send({poll:{title:window.__pollTitle.trim(),options:opts,votes:{}}});setPoll(false);window.__pollTitle="";window.__pollOptions=["",""]};

if(!room)return <div className="container"><form className="join-form" onSubmit={join}><div className="header-actions"><h1>Join Chat Room</h1><button type="button" className="settings-button" onClick={()=>setShowSettings(!showSettings)}>⚙ Settings</button></div>{showSettings&&<Settings settings={settings} update={updateSetting}/>}<input value={nickname} onChange={e=>{setNickname(e.target.value);localStorage.setItem("chatNickname",e.target.value)}} placeholder="Enter a nickname" required/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter chat code" required/><button type="submit">Join</button><div className="theme-selector"><span>Theme</span>{["light","dark","full","custom"].map(t=><button type="button" key={t} className={"theme-button "+((t==="full"?theme==="full-dark":theme===t)?"active":"")} onClick={()=>{const real=t==="full"?"full-dark":t;setThemeState(real);setTheme(real,custom);if(t==="custom")setShowCustom(!showCustom)}}>{t==="full"?"Full Dark":t[0].toUpperCase()+t.slice(1)}</button>)}</div>{showCustom&&theme==="custom"&&<Customize custom={custom} update={updateCustom}/>}<p className="join-note">Peer-to-peer room. Everyone using the same code joins the same WebRTC room.</p></form></div>;

return <div className="container"><div className={"chat-container size-"+settings.chatSize}><header className="chat-header"><div className="chat-title"><h2>#{room.code}</h2><span>{nickname}</span><span>● {online} connected</span></div><div className="header-actions"><button className={"tab-button "+(tab==="chat"?"active":"")} onClick={()=>setTab("chat")}>Chat</button><button className={"tab-button "+(tab==="screen"?"active":"")} onClick={()=>setTab("screen")}>Screen</button><button className="settings-button" onClick={()=>setShowSettings(!showSettings)}>⚙</button><button className="settings-button" onClick={leave}>Leave</button></div></header>{showSettings&&<Settings settings={settings} update={updateSetting}/>}
{tab==="chat"?<><main className="messages">{items.map(m=><Message key={m.id} message={m} username={nickname} isOwn={m.username===nickname} onDelete={id=>map.current?.delete(id)} onStartEdit={setEditing} onSaveEdit={edit} onCancelEdit={()=>setEditing(null)} isEditing={editing===m.id} formatMessageText={format} onSpeak={speak} ttsEnabled={settings.ttsEnabled} onVote={vote}/>) }{!items.length&&<div className="empty">No messages yet. Start the conversation.</div>}</main><div className="input-area"><div className="input-container">{settings.showTyping&&typing.length>0&&<div className="typing-indicator">{typing.join(", ")} {typing.length===1?"is":"are"} typing…</div>}<input value={text} onChange={typingChange} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send({})}}} placeholder="Write a message…"/><button onClick={speech}>🎤</button><button className={recording?"recording":""} onClick={recordAudio}>🎙</button><label className="file-label">📎<input type="file" hidden onChange={attach}/></label></div><button onClick={()=>setPoll(!poll)}>📊</button><button className={videoRecording?"recording":""} onClick={recordVideo}>🎥</button><button onClick={()=>send({})}>Send</button></div>{poll&&<PollBox close={()=>setPoll(false)} create={makePoll}/>}</>:<div className="screen-share-container"><div className="screen-share-header"><h3>Screen Share</h3><button className={screen?"screen-share-button active":"screen-share-button"} onClick={share}>{screen?"Stop sharing":"Share screen"}</button></div>{screen?<video ref={screenVideo} className="screen-preview" autoPlay muted playsInline/>:<div className="no-screens-message">Screen preview for this device.</div>}</div>}{toast&&<button className="toast" onClick={()=>setToast("")}>{toast}</button>}</div></div>
}

function Settings({settings,update}){return <div className="settings-panel"><div className="setting-row"><label>Show typing indicator</label><input type="checkbox" checked={settings.showTyping} onChange={e=>update("showTyping",e.target.checked)}/></div><div className="setting-row"><label>Chat size</label><select value={settings.chatSize} onChange={e=>update("chatSize",e.target.value)}><option value="small">Small</option><option value="normal">Normal</option><option value="large">Large</option></select></div><div className="setting-row"><label>Text to speech</label><input type="checkbox" checked={settings.ttsEnabled} onChange={e=>update("ttsEnabled",e.target.checked)}/></div><div className="setting-row"><label>Speech rate</label><input type="range" min=".5" max="2" step=".1" value={settings.ttsRate} onChange={e=>update("ttsRate",+e.target.value)}/></div><div className="setting-row"><label>Speech pitch</label><input type="range" min=".5" max="2" step=".1" value={settings.ttsPitch} onChange={e=>update("ttsPitch",+e.target.value)}/></div><div className="setting-row"><label>Speech language</label><select value={settings.sttLanguage} onChange={e=>update("sttLanguage",e.target.value)}><option>en-US</option><option>en-GB</option><option>no-NO</option><option>de-DE</option><option>fr-FR</option><option>es-ES</option></select></div></div>}
function Customize({custom,update}){const labels={bgColor:"Background",chatBg:"Chat",textColor:"Text",headerBg:"Header",messageBg:"Messages",messageOwnBg:"Own messages",borderColor:"Borders",inputBg:"Inputs",linkColor:"Links"};return <div className="color-picker-panel"><h3>Customize Theme</h3>{Object.entries(labels).map(([k,l])=><div className="color-picker-row" key={k}><label>{l}</label><input type="color" value={custom[k]} onChange={e=>update(k,e.target.value)}/></div>)}</div>}
function PollBox({close,create}){const[,force]=useState(0);window.__pollOptions=window.__pollOptions||["",""];return <div className="poll-creator"><input placeholder="Poll question" onChange={e=>window.__pollTitle=e.target.value}/>{window.__pollOptions.map((v,i)=><input key={i} defaultValue={v} placeholder={"Option "+(i+1)} onChange={e=>window.__pollOptions[i]=e.target.value}/>) }<button onClick={()=>{window.__pollOptions.push("");force(x=>x+1)}}>Add option</button><button onClick={create}>Create poll</button><button onClick={close}>Cancel</button></div>}
createRoot(document.getElementById("app")).render(<App/>);