/* Chat menu: Save, Load, Publish an Excel chat export. */
(() => {
'use strict';
const ROOM='public', TYPE='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', NAME='Chat-App-2-Chat-Export.xlsx', MAX=4*1024*1024, DB='chat-app2-local', STORE='messages';
const user=()=>localStorage.getItem('chat_username')||localStorage.getItem('chat_name')||'Someone';
const did=()=>localStorage.getItem('chat_device_id')||'';
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,2);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function getMessages(){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>res((r.result||[]).filter(m=>(m.room||m.channel)===ROOM).sort((a,b)=>new Date(a.created_at||0)-new Date(b.created_at||0)));r.onerror=()=>rej(r.error);});}
function download(raw,name=NAME){const u=URL.createObjectURL(new Blob([raw],{type:TYPE})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500);}
function b64(raw){let s='';for(let i=0;i<raw.length;i+=32768)s+=String.fromCharCode(...raw.subarray(i,i+32768));return btoa(s);}
function fromB64(s){const x=atob(s),o=new Uint8Array(x.length);for(let i=0;i<x.length;i++)o[i]=x.charCodeAt(i);return o;}
function makeMenu(){if(document.getElementById('saveChatMenu'))return;const o=document.createElement('div');o.id='saveChatMenu';o.className='overlay';o.innerHTML=`<div class="panel" style="max-width:430px"><div class="panel-header"><h2>📊 Chat</h2><button class="icon-btn" id="scClose">×</button></div><div class="panel-body"><p style="color:#9da5b0;line-height:1.5">Choose an action for the chat Excel file.</p><div style="display:grid;gap:10px"><button class="game-btn" id="scSave">💾 Save</button><button class="game-btn" id="scLoad">📂 Load</button><button class="game-btn" id="scPublish">📤 Publish</button></div><input id="scFile" type="file" accept=".xlsx,.xls" style="display:none"></div></div>`;document.body.appendChild(o);o.querySelector('#scClose').onclick=()=>o.classList.remove('show');o.querySelector('#scSave').onclick=save;o.querySelector('#scLoad').onclick=()=>pick('load');o.querySelector('#scPublish').onclick=()=>pick('publish');o.querySelector('#scFile').onchange=async e=>{const f=e.target.files?.[0],mode=e.target.dataset.mode;if(f)try{await processFile(f,mode);}catch(err){alert('Could not process the Excel chat: '+err.message);}e.target.value='';};}
function openMenu(){makeMenu();document.getElementById('saveChatMenu').classList.add('show');}
function pick(mode){const i=document.getElementById('scFile');i.dataset.mode=mode;i.click();}
async function save(){if(!window.XLSX)return alert('Excel support is still loading.');const ms=await getMessages();if(!ms.length)return alert('There are no Public Chat messages saved on this device yet.');const wb=XLSX.utils.book_new();const rows=ms.map(m=>({Time:m.created_at||'',Username:m.username||'',Message:m.message||'','Device ID':m.device_id||'',Edited:m.edited?'Yes':'No','Game Message':m.game_message?'Yes':'No'}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Chat');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Chat App 2 Export'],['Channel','# public'],['Messages',ms.length],['Exported by',user()],['Exported at',new Date().toISOString()]]),'Info');download(new Uint8Array(XLSX.write(wb,{bookType:'xlsx',type:'array'})));document.getElementById('saveChatMenu').classList.remove('show');}
async function processFile(file,mode){if(!window.XLSX)throw new Error('Excel support is still loading.');const raw=new Uint8Array(await file.arrayBuffer());if(mode==='publish')return publish(raw,file.name);return importRaw(raw);}
async function importRaw(raw){const wb=XLSX.read(raw,{type:'array'}),name=wb.SheetNames.includes('Chat')?'Chat':wb.SheetNames[0];if(!name)throw new Error('The Excel file has no sheets.');const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:''});const imported=rows.map((r,i)=>({id:'import-'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+i),username:String(r.Username||'Imported User').slice(0,24),channel:ROOM,room:ROOM,message:String(r.Message||'').slice(0,20000),device_id:String(r['Device ID']||'imported').slice(0,100),edited:String(r.Edited||'').toLowerCase()==='yes',created_at:r.Time&&!isNaN(Date.parse(r.Time))?new Date(r.Time).toISOString():new Date().toISOString(),game_message:String(r['Game Message']||'').toLowerCase()==='yes',p2p:true,imported_from_excel:true})).filter(m=>m.message||m.username);if(!imported.length)throw new Error('No chat messages were found.');const d=await openDB();await new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);imported.forEach(m=>s.put(m));tx.oncomplete=res;tx.onerror=()=>rej(tx.error||new Error('Import failed'));});imported.forEach(m=>window.dispatchEvent(new CustomEvent('chat:p2p-message',{detail:m})));document.getElementById('saveChatMenu')?.classList.remove('show');alert(`Loaded ${imported.length} messages into your local Public Chat.`);}
async function publish(raw,name){if(raw.byteLength>MAX)throw new Error('This Excel file is larger than 4 MB and cannot be published to everyone.');const body={id:'chat-excel-'+(crypto.randomUUID?crypto.randomUUID():Date.now()),username:user(),channel:ROOM,message:`📊 ${user()} asks everyone to load “${name}” into Public Chat.`,files:[{name,data:b64(raw),base64:true,type:TYPE,size:raw.byteLength,chatExport:true}],device_id:did(),created_at:new Date().toISOString(),invisible_to_others:false,game_message:false,p2p:true,chat_export_offer:true};const r=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`Publish failed (${r.status}).`);document.getElementById('saveChatMenu')?.classList.remove('show');alert('Published. Everyone will be asked whether they want to load the Excel chat.');}
function offer(message){if(!message?.chat_export_offer||message.device_id===did())return;const file=Array.isArray(message.files)&&message.files.find(f=>f?.chatExport);if(!file||document.getElementById('chatExcelOffer'))return;const o=document.createElement('div');o.id='chatExcelOffer';o.className='overlay';o.innerHTML=`<div class="panel" style="max-width:430px"><div class="panel-header"><h2>📊 Load Excel Chat?</h2><button class="icon-btn" id="eoClose">×</button></div><div class="panel-body"><p id="eoText" style="color:#9da5b0;line-height:1.5"></p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><button class="game-btn" id="eoNo">No</button><button class="game-btn" id="eoYes">Load Chat</button></div></div></div>`;document.body.appendChild(o);o.querySelector('#eoText').textContent=`${message.username||'Someone'} asks everyone to load “${file.name||'this Excel file'}” into Public Chat. Do you want to load it?`;o.querySelector('#eoClose').onclick=()=>o.remove();o.querySelector('#eoNo').onclick=()=>o.remove();o.querySelector('#eoYes').onclick=async()=>{try{await importRaw(fromB64(file.data));o.remove();}catch(e){alert('Could not load the Excel chat: '+e.message);}};o.classList.add('show');}
function install(){if(document.getElementById('saveChatBtn'))return;const a=document.querySelector('.header-actions');if(!a)return setTimeout(install,150);const b=document.createElement('button');b.className='icon-btn';b.id='saveChatBtn';b.title='Save / Load / Publish Chat';b.setAttribute('aria-label','Save / Load / Publish Chat');b.textContent='📊';b.onclick=openMenu;a.insertBefore(b,a.firstChild);}
window.addEventListener('chat:p2p-message',e=>offer(e.detail));install();
})();