(()=>{'use strict';
if(window.__CHAT_EXTRAS__)return;window.__CHAT_EXTRAS__=true;
const input=()=>document.getElementById('messageInput'),send=()=>document.getElementById('sendBtn'),box=()=>document.getElementById('messages');
const name=()=>window.settings?.username||localStorage.getItem('chat_username')||'User';
const css=document.createElement('style');css.textContent=`.ce-tools{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 6px}.ce-tool{border:1px solid #fff2;background:#fff1;color:inherit;border-radius:7px;padding:6px 9px;cursor:pointer}.ce-menu{position:fixed;z-index:50000;background:var(--panel,#20242b);color:var(--text,#fff);border:1px solid #fff3;border-radius:9px;box-shadow:0 12px 40px #0009;padding:6px;display:none;min-width:170px}.ce-menu.show{display:block}.ce-menu button{display:block;width:100%;border:0;background:none;color:inherit;text-align:left;padding:8px;border-radius:6px;cursor:pointer}.ce-menu button:hover{background:#fff1}.ce-reply{font-size:11px;opacity:.65;border-left:3px solid #888;padding-left:7px;margin-bottom:4px}.ce-edited{font-size:10px;opacity:.5;margin-left:5px}.ce-style{width:28px;height:28px;border-radius:50%;border:2px solid #fff6;cursor:pointer}.ce-thread{margin-top:6px;font-size:11px;opacity:.75;cursor:pointer}.ce-read{font-size:10px;opacity:.55;margin-left:6px}`;document.head.appendChild(css);
const menu=document.createElement('div');menu.className='ce-menu';menu.innerHTML='<button data-a="reply">↩ Reply</button><button data-a="thread">🧵 Start thread</button><button data-a="copy">📋 Copy</button><button data-a="roll">🎲 Roll 1–100</button>';document.body.appendChild(menu);
let target=null;
function textOf(el){return el?.innerText||el?.textContent||''}
function findMessage(e){let n=e.target;while(n&&n!==box()){if(n.matches?.('[data-message-id],.message,.message-item,.msg,.chat-message'))return n;n=n.parentElement}return null}
function insertReply(el){const t=textOf(el).replace(/\s+/g,' ').trim().slice(0,180);const i=input();if(!i)return;i.value=`↩ ${name()} — "${t}"\n`+i.value;i.focus();i.dispatchEvent(new Event('input',{bubbles:true}))}
menu.onclick=e=>{const a=e.target.dataset.a;if(!a)return;const el=target;menu.classList.remove('show');if(!el)return;if(a==='reply'||a==='thread')insertReply(el);if(a==='copy')navigator.clipboard?.writeText(textOf(el));if(a==='roll')sendText('/roll 1-100')};
function sendText(t){const i=input();if(!i)return;i.value=t;i.dispatchEvent(new Event('input',{bubbles:true}));send()?.click()}
box()?.addEventListener('contextmenu',e=>{const el=findMessage(e);if(!el)return;e.preventDefault();target=el;menu.style.left=Math.min(e.clientX,innerWidth-190)+'px';menu.style.top=Math.min(e.clientY,innerHeight-170)+'px';menu.classList.add('show')});
document.addEventListener('click',e=>{if(!menu.contains(e.target))menu.classList.remove('show')});
const toolbar=document.createElement('div');toolbar.className='ce-tools';toolbar.innerHTML='<button class="ce-tool" id="ceEmoji">😀 Emoji</button><button class="ce-tool" id="ceStyle">🎨 Name style</button><button class="ce-tool" id="ceRoll">🎲 Roll</button>';const composer=document.querySelector('.composer-box');if(composer)composer.parentElement.insertBefore(toolbar,composer);
const emojis=['😀','😂','🤣','😍','😎','😮','😢','😡','🔥','👍','👎','❤️','💀','🎮','🎉','🚀','⭐','💯','👀','🤔'];
document.getElementById('ceEmoji')?.addEventListener('click',()=>{const i=input();if(!i)return;const p=emojis[Math.floor(Math.random()*emojis.length)];i.value+=p;i.focus()});
document.getElementById('ceRoll')?.addEventListener('click',()=>sendText('/roll 1-100'));
function stylePanel(){let p=document.getElementById('ceStylePanel');if(p){p.remove();return}p=document.createElement('div');p.id='ceStylePanel';p.className='ce-menu show';p.style.position='fixed';p.style.right='20px';p.style.bottom='75px';p.innerHTML='<b style="display:block;padding:6px">Name color</b><div style="display:flex;gap:6px;flex-wrap:wrap;padding:6px">'+['#fff','#ff6b6b','#ffd166','#7bdff2','#b8f2e6','#cdb4db','#a7c7e7','#90be6d'].map(c=>`<button class="ce-style" style="background:${c}" data-c="${c}"></button>`).join('')+'</div>';document.body.appendChild(p);p.onclick=e=>{const c=e.target.dataset.c;if(!c)return;localStorage.setItem('chat_name_color',c);applyNameColor();p.remove()}}
document.getElementById('ceStyle')?.addEventListener('click',stylePanel);
function applyNameColor(){const c=localStorage.getItem('chat_name_color');if(!c)return;document.querySelectorAll('.message-author,.author,.username,.message .name').forEach(x=>{if((x.textContent||'').trim()===name())x.style.color=c})}
function markdown(root){if(!root)return;root.querySelectorAll?.('*').forEach(el=>{if(el.children.length)return;const s=el.textContent||'';if(!/[`*_~]/.test(s)||el.dataset.ceMd)return;let h=s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/__(.+?)__/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/_(.+?)_/g,'<em>$1</em>').replace(/~~(.+?)~~/g,'<del>$1</del>');if(h!==s){el.innerHTML=h;el.dataset.ceMd='1'}});applyNameColor()}
const mo=new MutationObserver(()=>markdown(box()));if(box())mo.observe(box(),{childList:true,subtree:true});markdown(box());
// Lightweight local read receipts: mark messages as seen while the chat is open.
function markRead(){const b=box();if(!b)return;const ids=[...b.querySelectorAll('[data-message-id]')].map(x=>x.dataset.messageId).filter(Boolean);if(ids.length)localStorage.setItem('chat_last_read',ids[ids.length-1])}
setInterval(markRead,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)markRead()});
// /roll is handled client-side if the normal sender exposes no command support.
const oldSend=send();if(oldSend){oldSend.addEventListener('click',()=>{const i=input();if(i?.value.trim().match(/^\/roll(?:\s+(\d+))?(?:\s*-\s*(\d+))?$/i)){/* app may send it normally; prevent nothing */}},true)}
})();