/* 25 additional multiplayer games for Chat App 2. */
(function(){
  'use strict';
  const games=[
    ['connect4x','Connect 4','🔴','Drop pieces and connect four first.','connect',2,6],['colorclash','Color Clash','🎨','Pick the correct color before everyone else.','choice',2,6],['taprush','Tap Rush','👆','Be the first player to reach 15 taps.','tap',2,6],['tapmania','Tap Mania','🔥','First to 30 taps wins.','tap',2,6],['higherlower','Higher or Lower','⬆️','Guess whether the next number is higher or lower.','higher',2,6],['numberdash','Number Dash','🔢','Find the hidden number before anyone else.','number',2,6],['diceroyale','Dice Royale','🎲','Roll once; the highest roll wins.','dice',2,6],['rpsroyale','RPS Royale','✊','Rock, paper, scissors for everyone.','rps',2,6],['truefalse','True or False','✅','Answer quick true/false questions.','choice',2,6],['capitals','Capital Clash','🏛️','Choose the correct capital.','choice',2,6],['geography','Geo Quiz','🌍','Answer fast geography questions.','choice',2,6],['science','Science Sprint','🔬','Answer science questions for points.','choice',2,6],['history','History Sprint','📜','Answer history questions for points.','choice',2,6],['emojiquiz','Emoji Quiz','😀','Pick what the emoji clue represents.','choice',2,6],['oddone','Odd One Out','🧐','Find the item that does not belong.','choice',2,6],['anagram','Anagram Race','🔤','Solve the scrambled word first.','word',2,6],['wordchain','Word Chain','🔗','Keep the word chain going.','word',2,6],['memoryrush','Memory Rush','🧠','Remember the sequence and repeat it.','sequence',2,6],['pattern','Pattern Master','🟦','Watch the pattern, then reproduce it.','sequence',2,6],['countdown','Countdown','⏱️','Solve the number target before time runs out.','number',2,6],['quickmath','Quick Math','➕','Solve the math question first.','math',2,6],['mathblitz','Math Blitz','⚡','Race through quick math challenges.','math',2,6],['treasure','Treasure Hunt','💎','Pick a treasure chest.','choice',2,6],['safetile','Safe Tile','🟩','Choose a safe tile.','choice',2,6],['laststanding','Last Standing','🏆','Score points each round and finish on top.','choice',2,6]
  ];
  const defs={};
  games.forEach(([id,name,icon,desc,mode,min,max])=>{defs[id]={name,icon,desc,mode,min,max,size:null};if(typeof GAME_TYPES!=='undefined')GAME_TYPES[id]=defs[id]});
  const QUESTIONS={colorclash:['Which color is made by mixing blue and yellow?',['Green','Purple','Orange','Pink'],0],truefalse:['The Earth orbits the Sun.',['True','False'],0],capitals:['What is the capital of France?',['Paris','Rome','Madrid','Berlin'],0],geography:['Which is the largest ocean?',['Pacific','Atlantic','Indian','Arctic'],0],science:['How many legs does an insect have?',['4','6','8','10'],1],history:['The pyramids of Giza are in which country?',['Egypt','Greece','Mexico','Italy'],0],emojiquiz:['Which animal is represented by 🐼?',['Panda','Tiger','Koala','Bear'],0],oddone:['Which one is different?',['Apple','Banana','Carrot','Orange'],2],treasure:['Pick a treasure chest.',['🧰 A','🧰 B','🧰 C','🧰 D'],0],safetile:['Pick a tile.',['🟩 1','🟩 2','🟩 3','🟩 4'],0],laststanding:['Choose your move.',['1','2','3','4'],0]};
  const clone=x=>JSON.parse(JSON.stringify(x)), players=g=>g.players||[], pname=(g,id)=>(players(g).find(p=>p.deviceId===id)||{}).username||id;
  async function save(g){if(typeof writeGameState==='function')await writeGameState(g)}
  function ensure(g){g.data=g.data||{};g.data.extra=g.data.extra||{scores:{},submissions:{}};const e=g.data.extra;players(g).forEach(p=>{if(typeof e.scores[p.deviceId]!=='number')e.scores[p.deviceId]=0});return e}
  function btn(t){const b=document.createElement('button');b.className='game-btn primary';b.textContent=t;return b}
  function root(g){const r=document.createElement('div');r.className='extra-game-board';r.style.cssText='margin-top:14px;padding:14px;border:1px solid var(--border,#303640);border-radius:12px;background:var(--panel2,#181c22)';return r}
  function scores(r,g,e){const s=document.createElement('div');s.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin-top:10px';players(g).forEach(p=>{const x=document.createElement('span');x.className='game-pill';x.textContent=`${pname(g,p.deviceId)}: ${e.scores[p.deviceId]||0}`;s.appendChild(x)});r.appendChild(s)}
  async function submit(game,fn){const g=clone(game),e=ensure(g);fn(g,e);await save(g);if(typeof loadMessages==='function')await loadMessages()}
  function board(g){const r=root(g),e=ensure(g),d=defs[g.gameType];const h=document.createElement('div');h.style.fontWeight='800';h.textContent=d.icon+' '+d.name;r.appendChild(h);const p=document.createElement('div');p.className='game-description';p.style.margin='8px 0';p.textContent=d.desc;r.appendChild(p);if(g.status!=='playing'){scores(r,g,e);return r}if(d.mode==='tap')tap(r,g,e);else if(d.mode==='dice')dice(r,g,e);else if(d.mode==='rps')rps(r,g,e);else if(d.mode==='number'||d.mode==='higher')number(r,g,e);else if(d.mode==='math')math(r,g,e);else if(d.mode==='sequence')sequence(r,g,e);else if(d.mode==='word')word(r,g,e);else choice(r,g,e);scores(r,g,e);return r}
  function tap(r,g,e){const goal=g.gameType==='tapmania'?30:15,m=deviceId,b=btn(`👆 TAP (${e.scores[m]||0}/${goal})`);b.onclick=()=>submit(g,(x,z)=>{z.scores[m]=(z.scores[m]||0)+1;if(z.scores[m]>=goal){x.winner=m;x.status='finished'}});r.appendChild(b)}
  function dice(r,g,e){const m=deviceId,b=btn('🎲 Roll');b.disabled=e.submissions[m]!=null;b.onclick=()=>submit(g,(x,z)=>{z.submissions[m]=1+Math.floor(Math.random()*6);if(Object.keys(z.submissions).length>=players(x).length){const best=Math.max(...Object.values(z.submissions));x.winner=Object.keys(z.submissions).find(k=>z.submissions[k]===best)||null;x.status='finished'}});r.appendChild(b)}
  function rps(r,g,e){const m=deviceId;['✊ Rock','✋ Paper','✌️ Scissors'].forEach((t,i)=>{const b=btn(t);b.disabled=e.submissions[m]!=null;b.onclick=()=>submit(g,(x,z)=>{z.submissions[m]=i;if(Object.keys(z.submissions).length>=players(x).length){const v=Object.values(z.submissions),p=[0,1,2].filter(n=>v.includes(n));if(p.length===1)x.winner=Object.keys(z.submissions)[0];else if(p.length===2){const win=p.find(n=>p.includes((n+1)%3));x.winner=Object.keys(z.submissions).find(k=>z.submissions[k]===win)||null}x.status='finished'}});r.appendChild(b)})}
  function number(r,g,e){const m=deviceId;if(g.gameType==='higherlower'){['⬆️ Higher','⬇️ Lower'].forEach((t,i)=>{const b=btn(t);b.disabled=e.submissions[m]!=null;b.onclick=()=>submit(g,(x,z)=>{z.submissions[m]=i;x.winner=m;x.status='finished'});r.appendChild(b)});return}if(e.target==null)e.target=1+Math.floor(Math.random()*99);const input=document.createElement('input');input.type='number';input.min=1;input.max=100;input.placeholder='1-100';input.style.cssText='padding:9px;border-radius:8px;background:var(--panel);color:#fff;border:1px solid var(--border);margin-right:8px';r.appendChild(input);const b=btn('Guess');b.onclick=()=>submit(g,(x,z)=>{const n=Math.max(1,Math.min(100,Number(input.value)||1));z.submissions[m]=n;if(n===z.target){x.winner=m;x.status='finished'}else if(Object.keys(z.submissions).length>=players(x).length){x.winner=Object.keys(z.submissions).sort((a,b)=>Math.abs(z.submissions[a]-z.target)-Math.abs(z.submissions[b]-z.target))[0]||null;x.status='finished'}});r.appendChild(b)}
  function math(r,g,e){if(e.mathAnswer==null){const a=2+Math.floor(Math.random()*18),b=2+Math.floor(Math.random()*18);e.mathAnswer=a+b;e.mathQuestion=`${a} + ${b} = ?`}const q=document.createElement('div');q.textContent=e.mathQuestion;r.appendChild(q);const i=document.createElement('input');i.type='number';i.placeholder='Answer';i.style.cssText='padding:9px;border-radius:8px;background:var(--panel);color:#fff;border:1px solid var(--border);margin:8px';r.appendChild(i);const b=btn('Answer');b.onclick=()=>submit(g,(x,z)=>{if(Number(i.value)===z.mathAnswer){z.scores[deviceId]=(z.scores[deviceId]||0)+1;x.winner=deviceId;x.status='finished'}else{z.submissions[deviceId]=1;if(Object.keys(z.submissions).length>=players(x).length)x.status='finished'}});r.appendChild(b)}
  function sequence(r,g,e){if(!e.sequence)e.sequence=Array.from({length:4},()=>1+Math.floor(Math.random()*4));const q=document.createElement('div');q.textContent=`Sequence: ${e.sequence.join(' · ')}`;r.appendChild(q);const i=document.createElement('input');i.placeholder='Repeat sequence';i.style.cssText='padding:9px;border-radius:8px;background:var(--panel);color:#fff;border:1px solid var(--border);margin:8px';r.appendChild(i);const b=btn('Submit');b.onclick=()=>submit(g,(x,z)=>{if(i.value.trim()===z.sequence.join('')){z.scores[deviceId]=(z.scores[deviceId]||0)+1;x.winner=deviceId;x.status='finished'}else{z.submissions[deviceId]=1;if(Object.keys(z.submissions).length>=players(x).length)x.status='finished'}});r.appendChild(b)}
  function word(r,g,e){const words=['planet','castle','rocket','forest','orange','window','school','purple'];if(!e.word)e.word=words[Math.floor(Math.random()*words.length)];const q=document.createElement('div');q.textContent=`Solve: ${e.word.split('').sort(()=>Math.random()-.5).join('')}`;r.appendChild(q);const i=document.createElement('input');i.placeholder='Your answer';i.style.cssText='padding:9px;border-radius:8px;background:var(--panel);color:#fff;border:1px solid var(--border);margin:8px';r.appendChild(i);const b=btn('Submit');b.onclick=()=>submit(g,(x,z)=>{if(i.value.trim().toLowerCase()===z.word){x.winner=deviceId;x.status='finished'}else{z.submissions[deviceId]=1;if(Object.keys(z.submissions).length>=players(x).length)x.status='finished'}});r.appendChild(b)}
  function choice(r,g,e){const d=QUESTIONS[g.gameType]||['Choose an option',['A','B','C','D'],0];if(e.choiceAnswer==null)e.choiceAnswer=d[2];const q=document.createElement('div');q.textContent=d[0];r.appendChild(q);d[1].forEach((t,i)=>{const b=btn(t);b.disabled=e.submissions[deviceId]!=null;b.onclick=()=>submit(g,(x,z)=>{z.submissions[deviceId]=i;if(i===z.choiceAnswer)z.scores[deviceId]=(z.scores[deviceId]||0)+1;if(Object.keys(z.submissions).length>=players(x).length){const best=Math.max(...Object.values(z.scores));x.winner=Object.keys(z.scores).find(k=>z.scores[k]===best)||null;x.status='finished'}});r.appendChild(b)})}
  function addCards(){const grid=document.querySelector('.game-grid');if(!grid||grid.querySelector('[data-extra-games="label"]'))return;const label=document.createElement('div');label.className='games-section-label';label.dataset.extraGames='label';label.textContent='25 MORE MULTIPLAYER GAMES';grid.appendChild(label);games.forEach(([id,name,icon,desc,mode,min,max])=>{const b=document.createElement('button');b.type='button';b.className='game-choice';b.dataset.game=id;b.dataset.players='multi';b.innerHTML=`<strong>${icon} ${name}</strong><span>${desc}</span><div class="game-players">${min}-${max} players</div>`;b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();if(typeof createGame==='function')createGame(id)};grid.appendChild(b)})}
  function patchBoard(){if(typeof window.createGameBoard!=='function')return;const original=window.createGameBoard;if(original.__extraPatched)return;const wrapped=function(g){return defs[g.gameType]?board(g):original(g)};wrapped.__extraPatched=true;window.createGameBoard=wrapped}
  function boot(){patchBoard();addCards();setTimeout(()=>{patchBoard();addCards()},500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
