(()=>{
'use strict';

const G=[
{id:'snake2',i:'🐍',n:'Snake Party',p:1,m:4,d:'1–4 players',c:'Arcade'},
{id:'dots',i:'🔵',n:'Dots',p:1,m:4,d:'1–4 players',c:'Strategy'},
{id:'tictac',i:'❌',n:'Tic-Tac-Toe',p:1,m:2,d:'1–2 players',c:'Board'},
{id:'connect',i:'🔴',n:'Connect Four',p:1,m:2,d:'1–2 players',c:'Board'},
{id:'reaction2',i:'⚡',n:'Reaction Battle',p:2,m:4,d:'2–4 players',c:'Party'},
{id:'quicktap',i:'👆',n:'Quick Tap',p:1,m:4,d:'1–4 players',c:'Party'},
{id:'nim',i:'🪵',n:'Take Away',p:1,m:2,d:'1–2 players',c:'Strategy'},
{id:'dice',i:'🎲',n:'Dice Duel',p:2,m:4,d:'2–4 players',c:'Party'},
{id:'memory2',i:'🧠',n:'Memory Match',p:1,m:4,d:'1–4 players',c:'Board'},
{id:'rps',i:'✊',n:'Rock Paper Scissors',p:1,m:2,d:'1–2 players',c:'Party'},
{id:'math',i:'➕',n:'Math Rush',p:1,m:4,d:'1–4 players',c:'Puzzle'},
{id:'higher',i:'⬆️',n:'Higher or Lower',p:1,m:4,d:'1–4 players',c:'Party'},
{id:'four',i:'🟡',n:'Four Corners',p:1,m:4,d:'1–4 players',c:'Party'},
{id:'color',i:'🎨',n:'Color Clash',p:1,m:4,d:'1–4 players',c:'Arcade'},
{id:'goal',i:'⚽',n:'Goal Rush',p:1,m:4,d:'1–4 players',c:'Arcade'},
{id:'typing2',i:'⌨️',n:'Typing Race',p:1,m:4,d:'1–4 players',c:'Skill'},
{id:'solo',i:'🎯',n:'Number Hunt',p:1,m:1,d:'1 player',c:'Solo'},
{id:'flappy2',i:'🐦',n:'Flappy',p:1,m:1,d:'1 player',c:'Solo'},
{id:'mines2',i:'💣',n:'Minesweeper',p:1,m:1,d:'1 player',c:'Solo'},
{id:'break2',i:'🧱',n:'Breakout',p:1,m:1,d:'1 player',c:'Solo'}
];
const css=document.createElement('style');css.textContent=`.gb-launch{margin:8px 0;width:100%;padding:13px;border:1px solid #fff2;border-radius:12px;background:#ffffff08;color:inherit;text-align:left;cursor:pointer}.gb-launch b{display:block}.gb-launch small{opacity:.6}.gb{position:fixed;inset:0;z-index:31000;background:#000b;display:none;align-items:center;justify-content:center;padding:16px}.gb.on{display:flex}.gbx{width:min(1050px,100%);height:min(900px,95vh);display:flex;flex-direction:column;overflow:hidden;background:var(--panel,#20242b);color:var(--text,#fff);border:1px solid #fff2;border-radius:16px}.gbh{display:flex;gap:8px;align-items:center;padding:14px;border-bottom:1px solid #fff2}.gbh h2{margin:0;flex:1}.gbb{border:0;border-radius:9px;padding:9px 12px;background:#fff1;color:inherit;cursor:pointer}.gbtools{display:grid;grid-template-columns:minmax(160px,1fr) auto auto;gap:8px;padding:12px;border-bottom:1px solid #fff2}.gbi,.gbs{min-width:0;padding:10px;border:1px solid #fff2;border-radius:9px;background:#ffffff08;color:inherit}.gbl{padding:14px;overflow:auto;display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:10px}.gbcard{border:1px solid #fff2;border-radius:12px;background:#ffffff07;color:inherit;padding:14px;text-align:left;cursor:pointer}.gbcard:hover{background:#fff1}.gbico{font-size:28px}.gbcard b{display:block;margin:6px 0 3px}.gbcard small{opacity:.6}.gbtag{display:inline-block;margin-top:7px;padding:3px 7px;border-radius:20px;background:#fff1;font-size:11px}.gbplay{padding:14px;overflow:auto}.gbcanvas{display:block;width:min(700px,100%);height:auto;margin:10px auto;border:1px solid #fff2;border-radius:12px;background:#080b10;touch-action:none}.gbcenter{text-align:center;padding:25px}.gbgrid{display:grid;gap:7px;max-width:500px;margin:15px auto}.gbcell{aspect-ratio:1;border:0;border-radius:9px;background:#ffffff0d;color:inherit;font-size:24px;font-weight:800;cursor:pointer}.gbcell:hover{background:#fff2}.gbrow{display:flex;justify-content:center;gap:8px;flex-wrap:wrap}.gbbig{font-size:44px;font-weight:900}.gbscore{text-align:center;font-size:18px;margin:10px}.gbinput{padding:12px;border:1px solid #fff2;border-radius:9px;background:#ffffff08;color:inherit}.gbhide{display:none!important}@media(max-width:650px){.gbtools{grid-template-columns:1fr 1fr}.gbl{grid-template-columns:1fr 1fr}.gbcard{padding:11px}}`;document.head.appendChild(css);
function esc(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
const ov=document.createElement('div');ov.className='gb';ov.innerHTML='<div class="gbx"><div class="gbh"><button class="gbb" id="gbback" style="display:none">← Games</button><h2 id="gbtitle">🎮 Games</h2><button class="gbb" id="gbclose">×</button></div><div id="gbbody"></div></div>';document.body.appendChild(ov);const body=ov.querySelector('#gbbody'),back=ov.querySelector('#gbback'),title=ov.querySelector('#gbtitle');let current=null,cleanup=()=>{};
function open(){ov.classList.add('on');list()}function close(){cleanup();cleanup=()=>{};ov.classList.remove('on')}
function list(){cleanup();cleanup=()=>{};back.style.display='none';title.textContent='🎮 Games';body.innerHTML='<div class="gbtools"><input class="gbi" id="q" placeholder="🔎 Search games..."><select class="gbs" id="players"><option value="all">Any players</option><option value="1">1 player</option><option value="2">Up to 2</option><option value="3">Up to 3</option><option value="4">Up to 4</option></select><select class="gbs" id="sort"><option value="low">Fewest players first</option><option value="high">Most players first</option><option value="name">Name A–Z</option><option value="cat">Category</option></select></div><div class="gbl" id="games"></div>';const q=body.querySelector('#q'),ps=body.querySelector('#players'),sort=body.querySelector('#sort'),out=body.querySelector('#games');function render(){let a=G.filter(x=>{let ok=!q.value||x.n.toLowerCase().includes(q.value.toLowerCase())||x.c.toLowerCase().includes(q.value.toLowerCase());if(ps.value!=='all')ok=ok&&x.p<=+ps.value&&x.m>=+ps.value;return ok});a.sort((x,y)=>sort.value==='low'?x.m-y.m:sort.value==='high'?y.m-x.m:sort.value==='cat'?x.c.localeCompare(y.c):x.n.localeCompare(y.n));out.innerHTML=a.length?a.map(x=>`<button class="gbcard" data-id="${x.id}"><span class="gbico">${x.i}</span><b>${esc(x.n)}</b><small>${esc(x.d)} · ${esc(x.c)}</small><span class="gbtag">${x.p===x.m&&x.p===1?'Solo':x.p+'–'+x.m+' players'}</span></button>`).join(''):'<div class="gbcenter">No games match those filters.</div>';out.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>play(b.dataset.id))}q.oninput=render;ps.onchange=render;sort.onchange=render;render()}
back.onclick=list;ov.querySelector('#gbclose').onclick=close;ov.onclick=e=>{if(e.target===ov)close()};
function play(id){cleanup();current=G.find(x=>x.id===id);back.style.display='block';title.textContent=current.i+' '+current.n;body.innerHTML='<div class="gbplay" id="gbplay"></div>';cleanup=games[id]?.(body.querySelector('#gbplay'))||(()=>{})}
const games={};
function common(el,players,desc){el.innerHTML=`<div class="gbscore">Players: <b>${players}</b> · ${desc}</div><div id="content"></div>`;return el.querySelector('#content')}
games.dice=el=>{const c=common(el,4,'Pass-and-play dice duel');c.innerHTML='<div class="gbcenter"><div class="gbbig" id="d">🎲</div><p id="m">Player 1 turn</p><button class="gbb" id="b">Roll</button><p id="scores"></p></div>';let p=1,s=[0,0,0,0];const b=c.querySelector('#b'),d=c.querySelector('#d'),m=c.querySelector('#m'),sc=c.querySelector('#scores');b.onclick=()=>{let v=1+Math.floor(Math.random()*6);s[p-1]+=v;d.textContent='🎲 '+v;if(s[p-1]>=30){m.textContent='🏆 Player '+p+' wins!';b.disabled=true}else{p=p%4+1;m.textContent='Player '+p+' turn'}sc.textContent=s.map((x,i)=>'P'+(i+1)+': '+x).join(' · ')};return()=>{}};
games.quicktap=el=>{const c=common(el,4,'Everyone takes turns on the same device');c.innerHTML='<div class="gbcenter"><div class="gbbig" id="n">READY?</div><p id="m">Press start.</p><button class="gbb" id="b">Start</button></div>';let p=1,score=[0,0,0,0],timer,go=false;b=c.querySelector('#b'),n=c.querySelector('#n'),m=c.querySelector('#m');b.onclick=()=>{if(go){score[p-1]++;p=p%4+1;m.textContent='Player '+p+' point!';n.textContent='⚡';go=false;clearTimeout(timer);setTimeout(()=>{go=true;n.textContent='TAP!';timer=setTimeout(()=>{go=false;n.textContent='⌛';m.textContent='Too slow — Player '+p+' missed'},900)},350)}else{go=true;n.textContent='WAIT…';m.textContent='Player '+p+' get ready';timer=setTimeout(()=>{go=true;n.textContent='TAP!'},700+Math.random()*1800)}};return()=>clearTimeout(timer)};
games.reaction2=games.quicktap;
games.rps=el=>{const c=common(el,2,'Two players choose without showing the other');c.innerHTML='<div class="gbcenter"><p>Player 1</p><div class="gbrow"><button class="gbb a">✊</button><button class="gbb a">✋</button><button class="gbb a">✌️</button></div><p id="m">Choose, then pass to Player 2.</p></div>';let a='';c.querySelectorAll('.a').forEach(b=>b.onclick=()=>{a=b.textContent;c.querySelector('#m').textContent='Player 2: choose your move';c.querySelectorAll('.a').forEach(x=>x.onclick=()=>{const z=x.textContent;let win=a===z?'Draw':(a==='✊'&&z==='✌️')||(a==='✋'&&z==='✊')||(a==='✌️'&&z==='✋');c.querySelector('#m').textContent=win?'🏆 Player 1 wins!':'🏆 Player 2 wins!';})});return()=>{}};
games.tictac=el=>{const c=common(el,2,'Local two-player board');c.innerHTML='<div class="gbgrid" id="g" style="grid-template-columns:repeat(3,1fr)"></div><div class="gbcenter" id="m">Player X turn</div>';let a=Array(9).fill(''),p='X',done=false,g=c.querySelector('#g'),m=c.querySelector('#m');function draw(){g.innerHTML=a.map((v,i)=>`<button class="gbcell">${v}</button>`).join('');g.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{if(done||a[i])return;a[i]=p;if([[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(x=>x.every(j=>a[j]===p))){done=true;m.textContent='🏆 Player '+p+' wins!'}else if(a.every(Boolean)){done=true;m.textContent='Draw!'}else{p=p==='X'?'O':'X';m.textContent='Player '+p+' turn'}draw()})}draw();return()=>{}};
games.connect=el=>{const c=common(el,2,'Local two-player Connect Four');c.innerHTML='<div class="gbgrid" id="g" style="grid-template-columns:repeat(7,1fr)"></div><div class="gbcenter" id="m">🔴 Player 1</div>';let a=Array(42).fill(''),p='R',done=false,g=c.querySelector('#g'),m=c.querySelector('#m');function win(v){for(let r=0;r<6;r++)for(let x=0;x<7;x++)for(const [dr,dx] of [[0,1],[1,0],[1,1],[1,-1]]){let n=0;for(let k=0;k<4;k++){let rr=r+dr*k,xx=x+dx*k;if(rr>=0&&rr<6&&xx>=0&&xx<7&&a[rr*7+xx]===v)n++;}if(n===4)return true}return false}function draw(){g.innerHTML=a.map(v=>`<button class="gbcell">${v==='R'?'🔴':v==='Y'?'🟡':''}</button>`).join('');g.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{if(done)return;let col=i%7;for(let r=5;r>=0;r--)if(!a[r*7+col]){a[r*7+col]=p;if(win(p)){done=true;m.textContent='🏆 '+(p==='R'?'Player 1':'Player 2')+' wins!'}else if(a.every(Boolean)){done=true;m.textContent='Draw!'}else{p=p==='R'?'Y':'R';m.textContent=p==='R'?'🔴 Player 1':'🟡 Player 2'}draw();return}})}draw();return()=>{}};
games.nim=el=>{const c=common(el,2,'Take 1–3 sticks; last stick wins');c.innerHTML='<div class="gbcenter"><div class="gbbig" id="s">🪵🪵🪵🪵🪵🪵🪵🪵🪵🪵</div><p id="m">Player 1</p><div class="gbrow">${[1,2,3].map(n=>`<button class="gbb" data-n="${n}">Take ${n}</button>`).join('')}</div></div>';let n=10,p=1,m=c.querySelector('#m'),s=c.querySelector('#s');c.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{if(n<=0)return;let x=Math.min(+b.dataset.n,n);n-=x;s.textContent='🪵'.repeat(n)||'—';if(!n)m.textContent='🏆 Player '+p+' wins!';else{p=p===1?2:1;m.textContent='Player '+p}});return()=>{}};
games.math=el=>{const c=common(el,4,'Each player answers a math question');c.innerHTML='<div class="gbcenter"><div class="gbbig" id="q">?</div><input class="gbinput" id="i" type="number"><p id="m">Player 1</p></div>';let p=1,score=[0,0,0,0],ans=0,q=c.querySelector('#q'),i=c.querySelector('#i'),m=c.querySelector('#m');function next(){let a=1+Math.floor(Math.random()*15),b=1+Math.floor(Math.random()*15);ans=a+b;q.textContent=a+' + '+b+' = ?';i.value='';i.focus()}i.onkeydown=e=>{if(e.key==='Enter'){if(+i.value===ans)score[p-1]++;p=p%4+1;m.textContent='Player '+p+' · Score: '+score.join(' / ');next()}};next();return()=>{}};
games.higher=el=>{const c=common(el,4,'Guess if the next number is higher or lower');c.innerHTML='<div class="gbcenter"><div class="gbbig" id="n">50</div><div class="gbrow"><button class="gbb" id="hi">Higher</button><button class="gbb" id="lo">Lower</button></div><p id="m">Player 1</p></div>';let n=50,p=1,s=[0,0,0,0],m=c.querySelector('#m');function guess(h){let x=1+Math.floor(Math.random()*100),ok=h?x>=n:x<=n;s[p-1]=ok?s[p-1]+1:Math.max(0,s[p-1]-1);n=x;p=p%4+1;m.textContent=(ok?'✓':'✗')+' · Player '+p+' · '+s.join(' / ');c.querySelector('#n').textContent=n}c.querySelector('#hi').onclick=()=>guess(true);c.querySelector('#lo').onclick=()=>guess(false);return()=>{}};
games.four=el=>{const c=common(el,4,'Pick one of four corners; one is the winner');c.innerHTML='<div class="gbgrid" style="grid-template-columns:1fr 1fr;max-width:420px">${[1,2,3,4].map(n=>`<button class="gbcell" data-n="${n}">Corner ${n}</button>`).join('')}</div><div class="gbcenter" id="m">Player 1 choose</div>';let p=1,m=c.querySelector('#m');c.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{let win=1+Math.floor(Math.random()*4);m.textContent=+b.dataset.n===win?'🏆 Player '+p+' wins this round!':'Not this time! Winning corner: '+win;p=p%4+1;m.textContent+=' · Player '+p+' turn'});return()=>{}};
games.color=el=>{const c=common(el,4,'Tap the color named by the word');const cols=['Red','Blue','Green','Yellow'];c.innerHTML='<div class="gbcenter"><div class="gbbig" id="w">RED</div><div class="gbrow">'+cols.map(x=>`<button class="gbb cc">${x}</button>`).join('')+'</div><p id="m">Player 1</p></div>';let p=1,s=[0,0,0,0],m=c.querySelector('#m'),w=c.querySelector('#w');function next(){w.textContent=cols[Math.floor(Math.random()*4)].toUpperCase();}c.querySelectorAll('.cc').forEach(b=>b.onclick=()=>{if(b.textContent===w.textContent)s[p-1]++;p=p%4+1;m.textContent='Player '+p+' · '+s.join(' / ');next()});next();return()=>{}};
games.goal=el=>{const c=common(el,4,'Choose a shot direction; score if you beat the keeper');c.innerHTML='<div class="gbcenter"><div class="gbbig">⚽</div><div class="gbrow">${['Left','Center','Right'].map(x=>`<button class="gbb shot">${x}</button>`).join('')}</div><p id="m">Player 1</p></div>';let p=1,s=[0,0,0,0],m=c.querySelector('#m');c.querySelectorAll('.shot').forEach(b=>b.onclick=()=>{if(Math.random()<.65)s[p-1]++;p=p%4+1;m.textContent='Player '+p+' · Goals: '+s.join(' / ') });return()=>{}};
games.typing2=el=>{const c=common(el,4,'Pass the keyboard to each player');const words=['galaxy','rocket','castle','banana','computer','rainbow','thunder'];let p=1,s=[0,0,0,0],start=0,word='';c.innerHTML='<div class="gbcenter"><div class="gbbig" id="w"></div><input class="gbinput" id="i" autocomplete="off"><p id="m"></p></div>';const w=c.querySelector('#w'),i=c.querySelector('#i'),m=c.querySelector('#m');function next(){word=words[Math.floor(Math.random()*words.length)];w.textContent=word;i.value='';start=performance.now();m.textContent='Player '+p}i.oninput=()=>{if(i.value===word){s[p-1]++;p=p%4+1;m.textContent='✓ '+Math.round(performance.now()-start)+'ms · Scores '+s.join(' / ');next()}};next();return()=>{}};
games.memory2=el=>{const c=common(el,4,'Everyone can play on the same board');let vals=['🍎','🍋','🍇','🍉','🍓','🥝','🍒','🥥'],cards=[...vals,...vals].sort(()=>Math.random()-.5),open=[],lock=false,p=1,moves=[0,0,0,0];c.innerHTML='<div class="gbgrid" id="g" style="grid-template-columns:repeat(4,1fr)"></div><div class="gbcenter" id="m">Player 1</div>';const g=c.querySelector('#g'),m=c.querySelector('#m');function draw(){g.innerHTML=cards.map((v,i)=>`<button class="gbcell" data-i="${i}">${open.includes(i)?v:'?'}</button>`).join('');g.querySelectorAll('button').forEach(b=>b.onclick=()=>flip(+b.dataset.i))}function flip(i){if(lock||open.includes(i)||open.length===2)return;open.push(i);draw();if(open.length===2){moves[p-1]++;lock=true;setTimeout(()=>{if(cards[open[0]]===cards[open[1]]){moves[p-1]++;m.textContent='🎉 Player '+p+' found a pair!'}else{open=[];p=p%4+1;m.textContent='Player '+p+' turn'}lock=false;draw()},450)}}draw();return()=>{}};
// Compatibility links: single-player games in the existing Solo Arcade stay available; this browser adds the expanded universal catalog.
function add(){if(document.querySelector('.gb-launch'))return;const anchor=document.getElementById('gamesOverlay');if(!anchor)return;const panel=anchor.querySelector('.panel-body');if(!panel)return;const b=document.createElement('button');b.className='gb-launch';b.innerHTML='<b>🎮 All Games — 1 to 4 Players</b><small>Search, filter by player count, sort from fewest to most players, and play local multiplayer.</small>';b.onclick=open;panel.insertBefore(b,panel.firstChild)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();window.addEventListener('load',add);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&ov.classList.contains('on'))close()});
})();