(()=>{
'use strict';
if(window.__expandedGamesLoader)return;
window.__expandedGamesLoader=true;
const loadFix=(src,key)=>{if(document.querySelector('script[data-chatapp-fix="'+key+'"]'))return;const s=document.createElement('script');s.src=src;s.dataset.chatappFix=key;s.async=false;document.body.appendChild(s)};
const loadBrowser=()=>{if(document.querySelector('script[data-expanded-games]'))return;const s=document.createElement('script');s.src='games-browser.js?v=20260901';s.dataset.expandedGames='1';document.body.appendChild(s)};
const openBrowser=()=>{const launcher=document.querySelector('.gb-launch');if(launcher)launcher.click();else{loadBrowser();setTimeout(()=>{const b=document.querySelector('.gb-launch');if(b)b.click()},300)}};
const add=()=>{const grid=document.querySelector('.game-grid');if(!grid)return false;if(grid.querySelector('.expanded-games-launch'))return true;const section=document.createElement('div');section.className='game-section-title';section.textContent='🎮 SOLO + PARTY GAMES';grid.insertBefore(section,grid.firstChild);const button=document.createElement('button');button.className='game-choice expanded-games-launch game-choice-featured';button.type='button';button.innerHTML='<strong>🕹️ Expanded Games Library</strong><span>20+ extra games • 1–4 players • Search & filters</span><div class="game-details"><b>Includes</b> · Solo games, local multiplayer, party games, arcade, puzzle and strategy games.<br>Search by name and filter from 1 player up to 4 players.</div><div class="game-players">1–4 players</div>';button.onclick=openBrowser;grid.insertBefore(button,grid.children[1]||null);return true};
const start=()=>{loadBrowser();loadFix('/screen-share-fix.js','screen-share');loadFix('/games-fast-sync.js','games-fast-sync');loadFix('/site-update.js','site-update');loadFix('/audio-compressor.js','audio-compressor');let tries=0;const timer=setInterval(()=>{tries++;if(add()||tries>=40)clearInterval(timer)},250)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('load',start,{once:true});
})();