(()=>{'use strict';
const API='/api/messages';
const device=()=>localStorage.getItem('chat_device_id')||'';
const username=()=>localStorage.getItem('chat_username')||window.settings?.username||'User';
const channel=()=>window.CHANNEL||'general';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=document.createElement('style');css.textContent=`.msgctx{position:fixed;z-index:50000;min-width:190px;background:var(--panel,#20242b);color:var(--text,#fff);border:1px solid #fff2;border-radius:10px;box-shadow:0 14px 45px #0009;padding:5px;display:none}.msgctx.show{display:block}.msgctx button{display:block;width:100%;border:0;background:transparent;color:inherit;text-align:left;padding:10px 12px;border-radius:7px;cursor:pointer;font:inherit}.msgctx button:hover{background:#fff1}.msgctx .danger{color:#ff7777}.msgctx .disabled{opacity:.45;cursor:default}.msg-reply{position:fixed;z-index:49999;left:50%;bottom:72px;transform:translateX(-50%);width:min(650px,calc(100vw - 20px));background:var(--panel,#20242b);border:1px solid #fff2;border-radius:10px;padding:9px 12px;display:none;box-shadow:0 10px 35px #0008}.msg-reply.show{display:flex;align-items:center;gap:10px}.msg-reply-info{flex:1;min-width:0}.msg-reply-info b{display:block}.msg-reply-info span{display:block;opacity:.65;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.msg-reply button{border:0;background:#fff1;color:inherit;border-radius:7px;padding:6px 9px;cursor:pointer}.msgedit{position:fixed;z-index:50001;left:50%;top:50%;transform:translate(-50%,-50%);width:min(520px,calc(100vw - 30px));background:var(--panel,#20242b);color:var(--text,#fff);border:1px solid #fff2;border-radius:12px;box-shadow:0 20px 70px #000b;padding:16px;display:none}.msgedit.show{display:block}.msgedit textarea{width:100%;box-sizing:border-box;min-height:110px;resize:vertical;background:#0003;color:inherit;border:1px solid #fff2;border-radius:8px;padding:10px;font:inherit}.msgedit-actions{display:flex;gap:8px;margin-top:10px}.msgedit-actions button{flex:1;padding:9px;border-radius:8px;border:1px solid #fff2;background:#fff1;color:inherit;cursor:pointer}.msgedit-actions .save{font-weight:700}`;document.head.appendChild(css);
const menu=document.createElement('div');menu.className='msgctx';menu.innerHTML='<button id="mreply">Reply</button><button id="medit">Edit message</button><button id="mdelete" class="danger">Delete message</button>';document.body.appendChild(menu);
const reply=document.createElement('div');reply.className='msg-reply';reply.innerHTML='<div class="msg-reply-info"><b id="mrwho">Replying to</b><span id="mrtext"></span></div><button id="mrcancel">Cancel</button>';document.body.appendChild(reply);
const edit=document.createElement('div');edit.className='msgedit';edit.innerHTML='<b>Edit message</b><textarea id="metext"></textarea><div class="msgedit-actions"><button id="mecancel">Cancel</button><button id="mesave" class="save">Save</button></div>';document.body.appendChild(edit);
const et=edit.querySelector('#metext');let target=null,replyTarget=null;
function closeMenu(){menu.classList.remove('show');target=null}
function getId(el){let n=el;while(n&&n!==document.body){if(n.dataset?.id&&!String(n.dataset.id).startsWith('game_'))return n.dataset.id;n=n.parentElement}return null}
function getMsg(el,id){const raw=el?.dataset?.message;if(raw){try{return JSON.parse(raw)}catch{}}return null}
function own(msg){return !!msg&&(msg.device_id===device()||msg.username===username())}
function findText(el){return el?.querySelector?.('.message-text')?.textContent?.trim()||el?.querySelector?.('.message-content')?.textContent?.trim()||''}
function request(method,body){return fetch(API,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'}).then(async r=>{let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Request failed');return d})}
function reload(){if(typeof window.loadMessages==='function')return Promise.resolve(window.loadMessages());return Promise.resolve(location.reload())}
function openMenu(el,x,y){const id=getId(el);if(!id)return;target=el;const msg=getMsg(el,id);const isMine=own(msg)||el.dataset.mine==='true'||el.classList.contains('mine');menu.querySelector('#medit').classList.toggle('disabled',!isMine);menu.querySelector('#mdelete').classList.toggle('disabled',!isMine);menu.style.left=Math.max(6,Math.min(x,innerWidth-205))+'px';menu.style.top=Math.max(6,Math.min(y,innerHeight-145))+'px';menu.classList.add('show')}
menu.querySelector('#mreply').onclick=()=>{const el=target;if(!el)return;const id=getId(el),msg=getMsg(el,id);replyTarget={id,username:msg?.username||el.dataset.username||'User',text:msg?.message||findText(el)};reply.querySelector('#mrwho').textContent='Replying to '+replyTarget.username;reply.querySelector('#mrtext').textContent=replyTarget.text||'(attachment)';reply.classList.add('show');menu.classList.remove('show');const input=document.getElementById('messageInput');if(input){input.focus();input.placeholder='Reply to '+replyTarget.username+'…'}};
reply.querySelector('#mrcancel').onclick=()=>{replyTarget=null;reply.classList.remove('show');const input=document.getElementById('messageInput');if(input)input.placeholder='Message #general · '};
menu.querySelector('#medit').onclick=()=>{const el=target;if(!el)return;const id=getId(el),msg=getMsg(el,id);if(!(own(msg)||el.dataset.mine==='true'||el.classList.contains('mine'))){closeMenu();return}et.value=msg?.message??findText(el);edit.dataset.id=id;edit.classList.add('show');menu.classList.remove('show');et.focus()};
menu.querySelector('#mdelete').onclick=async()=>{const el=target;if(!el)return;const id=getId(el),msg=getMsg(el,id);if(!(own(msg)||el.dataset.mine==='true'||el.classList.contains('mine'))){closeMenu();return}closeMenu();if(!confirm('Delete this message?'))return;try{await request('DELETE',{id,device_id:device(),channel:channel()});await reload()}catch(e){alert(e.message||'Could not delete message.')}};
edit.querySelector('#mecancel').onclick=()=>edit.classList.remove('show');
edit.querySelector('#mesave').onclick=async()=>{const id=edit.dataset.id,v=et.value.trim();if(!id||!v)return;try{await request('PATCH',{id,device_id:device(),message:v,channel:channel()});edit.classList.remove('show');await reload()}catch(e){alert(e.message||'Could not edit message.')}};
document.addEventListener('contextmenu',e=>{const el=e.target.closest?.('[data-id]');if(!el||!document.getElementById('messages')?.contains(el))return;e.preventDefault();openMenu(el,e.clientX,e.clientY)});
let lastTap=0;document.addEventListener('touchend',e=>{const el=e.target.closest?.('[data-id]');if(!el||!document.getElementById('messages')?.contains(el))return;const now=Date.now();if(now-lastTap<330){e.preventDefault();const t=e.changedTouches[0];openMenu(el,t?.clientX||innerWidth/2,t?.clientY||innerHeight/2);lastTap=0}else lastTap=now},{passive:false});
document.addEventListener('click',e=>{if(!menu.contains(e.target))menu.classList.remove('show')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.classList.remove('show');edit.classList.remove('show');reply.classList.remove('show')}});
})();