(()=>{'use strict';
if(window.__pollsLoaded)return;window.__pollsLoaded=true;
const API='/api/messages',PREFIX='__CHAT_POLL__:',VOTE='__CHAT_POLL_VOTE__:';
const device=()=>{let x=localStorage.getItem('chat_device_id');if(!x){x=crypto.randomUUID?crypto.randomUUID():'poll-'+Date.now()+'-'+Math.random();localStorage.setItem('chat_device_id',x)}return x};
const user=()=>window.settings?.username||localStorage.getItem('chat_username')||'User';
const channel=()=>window.CHANNEL||'general';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const css=document.createElement('style');css.textContent=`.poll-card{margin:8px 0;padding:14px;border:1px solid #fff2;border-radius:12px;background:var(--panel,#20242b);color:var(--text,#fff);box-shadow:0 6px 25px #0004}.poll-head{display:flex;gap:8px;align-items:center}.poll-head b{flex:1}.poll-meta{font-size:11px;opacity:.65;margin:5px 0 12px}.poll-q{font-size:17px;font-weight:700;margin-bottom:12px;white-space:pre-wrap}.poll-opt{width:100%;text-align:left;padding:9px 10px;margin:5px 0;border:1px solid #fff2;border-radius:8px;background:#fff1;color:inherit;cursor:pointer;position:relative;overflow:hidden}.poll-opt:disabled{cursor:default;opacity:.95}.poll-fill{position:absolute;inset:0 auto 0 0;width:0;background:#fff2;pointer-events:none}.poll-row{position:relative;z-index:1;display:flex;justify-content:space-between;gap:8px}.poll-pct{font-weight:700}.poll-votes{font-size:11px;opacity:.7;margin-top:8px}.poll-expired{opacity:.65}.poll-create{position:fixed;inset:0;z-index:31000;display:none;align-items:center;justify-content:center;background:#000b;padding:18px}.poll-create.show{display:flex}.poll-box{width:min(620px,96vw);max-height:92vh;overflow:auto;background:var(--panel,#20242b);color:var(--text,#fff);border:1px solid #fff3;border-radius:12px;padding:16px}.poll-title{display:flex;align-items:center;gap:10px}.poll-title b{flex:1}.poll-input,.poll-number{box-sizing:border-box;width:100%;padding:9px;border-radius:8px;border:1px solid #fff2;background:#fff1;color:inherit}.poll-field{display:grid;gap:6px;margin:10px 0}.poll-options{display:grid;gap:7px}.poll-option-line{display:flex;gap:7px}.poll-option-line input{flex:1}.poll-option-line button{width:38px;border:1px solid #fff2;background:#fff1;color:inherit;border-radius:8px;cursor:pointer}.poll-actions{display:flex;gap:8px;margin-top:14px}.poll-actions button{flex:1;padding:10px;border-radius:8px;border:1px solid #fff2;background:#fff1;color:inherit;cursor:pointer;font-weight:600}.poll-add{padding:8px 10px;border:1px solid #fff2;background:#fff1;color:inherit;border-radius:8px;cursor:pointer}.poll-empty{font-size:12px;opacity:.6}`;document.head.appendChild(css);
function addButton(){if(document.getElementById('pollCreateBtn'))return;const b=document.createElement('button');b.id='pollCreateBtn';b.type='button';b.className='attach-btn';b.title='Create Poll';b.setAttribute('aria-label','Create Poll');b.textContent='📊';const anchor=document.getElementById('attachBtn')||document.getElementById('voiceBtn')||document.getElementById('sendBtn');if(anchor?.parentNode)anchor.parentNode.insertBefore(b,anchor);else document.body.appendChild(b);b.onclick=openCreator}
const modal=document.createElement('div');modal.className='poll-create';modal.innerHTML=`<div class="poll-box"><div class="poll-title"><b>📊 Create Poll</b><button id="pollClose" class="poll-add">×</button></div><div class="poll-field"><label>Question</label><input id="pollQuestion" class="poll-input" maxlength="500" placeholder="Ask a question..."></div><div class="poll-field"><label>Duration (minutes)</label><input id="pollDuration" class="poll-number" type="number" min="1" max="10080" value="60"></div><div class="poll-field"><label>Answers (2–20)</label><div id="pollOptions" class="poll-options"></div><button id="pollAdd" class="poll-add">＋ Add answer</button></div><div class="poll-actions"><button id="pollCancel">Cancel</button><button id="pollCreate">Create Poll</button></div></div>`;document.body.appendChild(modal);
const q=modal.querySelector('#pollQuestion'),duration=modal.querySelector('#pollDuration'),optionsEl=modal.querySelector('#pollOptions');
function optionRow(value=''){const row=document.createElement('div');row.className='poll-option-line';row.innerHTML=`<input class="poll-input" maxlength="200" placeholder="Answer"><button type="button">×</button>`;row.querySelector('input').value=value;row.querySelector('button').onclick=()=>{if(optionsEl.children.length>2)row.remove()};optionsEl.appendChild(row)}
optionRow('');optionRow('');
function openCreator(){modal.classList.add('show');q.focus()};function closeCreator(){modal.classList.remove('show')}
modal.querySelector('#pollClose').onclick=closeCreator;modal.querySelector('#pollCancel').onclick=closeCreator;modal.querySelector('#pollAdd').onclick=()=>{if(optionsEl.children.length<20)optionRow('');else alert('A poll can have up to 20 answers.')};
async function post(message){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user(),channel:channel(),device_id:device(),message})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Could not send poll');return d}
modal.querySelector('#pollCreate').onclick=async()=>{const question=q.value.trim();const opts=[...optionsEl.querySelectorAll('input')].map(x=>x.value.trim()).filter(Boolean);const mins=Math.max(1,Math.min(10080,Number(duration.value)||60));if(!question)return alert('Enter a question.');if(opts.length<2||opts.length>20)return alert('Use between 2 and 20 answers.');const id=(crypto.randomUUID?crypto.randomUUID():'p-'+Date.now()+'-'+Math.random()).replace(/[^a-zA-Z0-9_-]/g,'');const poll={type:'poll',id,question,options:opts,duration:mins*60000,creator:user(),creatorDeviceId:device(),createdAt:Date.now()};try{await post(PREFIX+JSON.stringify(poll));localStorage.removeItem('poll_votes_'+id);closeCreator();q.value='';duration.value='60';optionsEl.innerHTML='';optionRow('');optionRow('')}catch(e){alert(e.message)}};
function parsePoll(m){if(typeof m!=='string'||!m.startsWith(PREFIX))return null;try{const p=JSON.parse(m.slice(PREFIX.length));return p.type==='poll'&&p.id&&Array.isArray(p.options)&&p.options.length>=2?p:null}catch{return null}}
function parseVote(m){if(typeof m!=='string'||!m.startsWith(VOTE))return null;try{const v=JSON.parse(m.slice(VOTE.length));return v.type==='vote'&&v.pollId&&Number.isInteger(v.option)?v:null}catch{return null}}
async function getMessages(){const r=await fetch(API+'?channel='+encodeURIComponent(channel())+'&_='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Poll refresh failed');const d=await r.json();return Array.isArray(d.messages)?d.messages:[]}
async function vote(p,index){const key='poll_votes_'+p.id;if(localStorage.getItem(key)!=null)return;const now=Date.now();const created=Number(p.createdAt)||now;if(now>created+(Number(p.duration)||0))return;try{await post(VOTE+JSON.stringify({type:'vote',pollId:p.id,option:index,deviceId:device(),username:user(),votedAt:now}));localStorage.setItem(key,String(index));await render()}catch(e){console.warn('Poll vote failed',e)}}
function removeProtocolMessages(){const root=document.getElementById('messages');if(!root)return;for(const el of [...root.children]){const t=el.textContent||'';if(t.includes(PREFIX)||t.includes(VOTE))el.style.display='none'}}
function card(p,votes){const total=votes.length;const counts=p.options.map((_,i)=>votes.filter(v=>v.option===i).length);const mine=localStorage.getItem('poll_votes_'+p.id);const ended=Date.now()>(Number(p.createdAt)||0)+(Number(p.duration)||0);const c=document.createElement('div');c.className='poll-card'+(ended?' poll-expired':'');const left=Math.max(0,(Number(p.createdAt)||0)+(Number(p.duration)||0)-Date.now());const mins=Math.ceil(left/60000);c.innerHTML=`<div class="poll-head"><b>📊 Poll</b><span>${ended?'Ended':mins+' min left'}</span></div><div class="poll-meta">${esc(p.creator||'User')} · ${total} vote${total===1?'':'s'}</div><div class="poll-q">${esc(p.question)}</div>`;p.options.forEach((o,i)=>{const n=counts[i],pct=total?Math.round(n/total*100):0;const b=document.createElement('button');b.className='poll-opt';b.disabled=ended||mine!==null;b.innerHTML=`<span class="poll-fill" style="width:${pct}%"></span><span class="poll-row"><span>${esc(o)}</span><span class="poll-pct">${pct}% · ${n}</span></span>`;b.onclick=()=>vote(p,i);c.appendChild(b)});const f=document.createElement('div');f.className='poll-votes';f.textContent=mine!==null?'You voted · everyone can see the results.':ended?'Voting has ended.':'Choose one answer.';c.appendChild(f);return c}
let lastSignature='';let running=false;
async function render(){if(running)return;running=true;try{const msgs=await getMessages();const polls=msgs.map(m=>({m,p:parsePoll(m.message)})).filter(x=>x.p);const votes=msgs.map(m=>parseVote(m.message)).filter(Boolean);removeProtocolMessages();const root=document.getElementById('messages');if(!root)return;root.querySelectorAll('.poll-card').forEach(x=>x.remove());for(const {p} of polls){const c=card(p,votes.filter(v=>v.pollId===p.id&&v.option>=0&&v.option<p.options.length));root.insertBefore(c,root.firstChild)}lastSignature=msgs.length+':'+polls.length+':'+votes.length}catch(e){console.warn('Poll render:',e)}finally{running=false}}
addButton();new MutationObserver(()=>{addButton();removeProtocolMessages()}).observe(document.body,{childList:true,subtree:true});setInterval(render,1000);render();
})();