/* Persistent profile login */
(()=>{
'use strict';
const D='chat_device_id',N='chat_username',P='chat_profile_picture_url',L='chat_profile_logged_in';
function deviceId(){let id=localStorage.getItem(D);if(!id){id=crypto.randomUUID?crypto.randomUUID():'device-'+Date.now();localStorage.setItem(D,id)}return id}
function style(){if(document.getElementById('profile-login-style'))return;const s=document.createElement('style');s.id='profile-login-style';s.textContent='#profileLoginGate{position:fixed;inset:0;z-index:50000;display:flex;align-items:center;justify-content:center;padding:24px;background:rgba(8,10,14,.98);font-family:Inter,Arial,sans-serif}#profileLoginGate .pl-card{width:min(440px,94vw);padding:30px;border:1px solid rgba(255,255,255,.1);border-radius:24px;background:#181b22;box-shadow:0 25px 90px rgba(0,0,0,.55)}#profileLoginGate h1{margin:0 0 8px;color:#fff;font-size:29px}#profileLoginGate p{margin:0 0 20px;color:#9da5b0;line-height:1.5}.pl-preview{width:96px;height:96px;border-radius:50%;object-fit:cover;background:#303641;border:2px solid rgba(255,255,255,.12);display:block;margin:0 auto 20px}.pl-label{display:block;margin:14px 0 7px;color:#c8ced7;font-size:13px;font-weight:700}.pl-input{width:100%;padding:12px 13px;border:1px solid #3a414c;border-radius:11px;background:#15181d;color:#fff;outline:none;font:inherit}.pl-device{font:11px ui-monospace,Consolas,monospace;color:#8f98a5;word-break:break-all;background:#111419;border:1px solid #292e36;border-radius:10px;padding:10px}.pl-login{width:100%;margin-top:20px;padding:13px;border:0;border-radius:12px;background:#6654e8;color:#fff;font-weight:800;font-size:15px;cursor:pointer}.pl-login:disabled{opacity:.55}.pl-status{min-height:18px;margin-top:10px;text-align:center;color:#929aa5;font-size:12px}';document.head.appendChild(s)}
function avatar(){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96"><rect width="100%" height="100%" fill="#303641"/><text x="50%" y="57%" text-anchor="middle" font-size="42" fill="#9da5b0">?</text></svg>')}
function finish(p){if(p?.username)localStorage.setItem(N,p.username);if(p?.pfp_url)localStorage.setItem(P,p.pfp_url);localStorage.setItem(L,'true');window.chatSupabaseProfile=p;document.getElementById('profileLoginGate')?.remove();window.dispatchEvent(new CustomEvent('chat:profile-login',{detail:p}))}
async function init(){style();const id=deviceId();let p=null;try{if(window.chatSupabaseApi?.loadProfileForDevice)p=await window.chatSupabaseApi.loadProfileForDevice(id)}catch(e){console.warn('[Profile] load failed',e)}
if(p?.username){finish(p);return}
const g=document.createElement('div');g.id='profileLoginGate';g.innerHTML='<div class="pl-card"><h1>Your Profile</h1><p>Your Device ID is permanent for this browser. Your Supabase profile and messages stay linked to it across refreshes and reopening.</p><img class="pl-preview" id="plPreview"><label class="pl-label">Name</label><input class="pl-input" id="plName" maxlength="24" placeholder="Your name"><label class="pl-label">Device ID</label><div class="pl-device" id="plDevice"></div><label class="pl-label">Profile picture</label><input class="pl-input" id="plPfp" type="file" accept="image/*"><button class="pl-login" id="plLogin">Log In</button><div class="pl-status" id="plStatus">Connecting to server…</div></div>';document.body.appendChild(g);
const n=g.querySelector('#plName'),f=g.querySelector('#plPfp'),v=g.querySelector('#plPreview'),d=g.querySelector('#plDevice'),b=g.querySelector('#plLogin'),st=g.querySelector('#plStatus');n.value=localStorage.getItem(N)||'';v.src=localStorage.getItem(P)||avatar();d.textContent=id;
f.onchange=()=>{const x=f.files?.[0];if(x)v.src=URL.createObjectURL(x)};
if(window.chatSupabaseApi?.saveProfileForDevice){st.textContent='Ready — log in to enter Public Chat.'}else{st.textContent='Server connection is unavailable.';b.disabled=true}
b.onclick=async()=>{const name=n.value.trim().slice(0,24);if(!name){st.textContent='Enter a name first.';return}b.disabled=true;st.textContent='Logging in…';try{const saved=await window.chatSupabaseApi.saveProfileForDevice({device_id:id,username:name,file:f.files?.[0]||null});finish(saved)}catch(e){console.error('[Profile] login failed',e);st.textContent='Could not connect/login: '+(e?.message||'Unknown error');b.disabled=false}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
