(()=>{
'use strict';
const btn=document.getElementById('screenShareHeaderBtn');if(!btn)return;
const API='/api/screen-share',Q=[150,300,450,600,750],F=[5,10,15,20,25,30];
let q=+localStorage.getItem('screen_share_quality')||750,f=+localStorage.getItem('screen_share_fps')||30,shareAudio=localStorage.getItem('screen_share_audio')!=='0';if(!Q.includes(q))q=750;if(!F.includes(f))f=30;
let peer=null,stream=null,sid='',sharing=false,watching=false,frozen=false,hb=null,hostCalls=new Map(),watchPeerId='',viewerHidden=false,lastLiveKey=null;
const device=()=>{let x=localStorage.getItem('chat_device_id');if(!x){x=crypto.randomUUID?crypto.randomUUID():'ss-'+Date.now()+Math.random();localStorage.setItem('chat_device_id',x)}return x};
const user=()=>window.settings?.username||localStorage.getItem('chat_username')||'User',channel=()=>window.CHANNEL||'general';
const css=document.createElement('style');css.textContent=`.ss-o{position:fixed;inset:0;z-index:20000;display:none;align-items:flex-start;justify-content:flex-end;padding:80px 18px;background:transparent;pointer-events:none}.ss-o.show{display:flex}.ss-box{pointer-events:auto;width:min(400px,calc(100vw - 36px));background:var(--panel,#20242b);color:var(--text,#fff);border:1px solid #fff2;border-radius:12px;box-shadow:0 20px 60px #0009;overflow:hidden}.ss-h{display:flex;align-items:center;gap:10px;padding:13px 15px;border-bottom:1px solid #fff2}.ss-h b{flex:1}.ss-x{border:0;background:none;color:inherit;font-size:22px;cursor:pointer}.ss-b{display:grid;gap:12px;padding:15px}.ss-f{display:grid;gap:6px}.ss-f label,.ss-note{font-size:12px;opacity:.7}.ss-s,.ss-btn{width:100%;box-sizing:border-box;padding:10px;border-radius:8px;border:1px solid #fff2;background:#fff1;color:inherit}.ss-btn{cursor:pointer;font-weight:600}.ss-toggle{display:flex;align-items:center;justify-content:space-between;padding:10px;border:1px solid #fff2;border-radius:8px}.ss-toggle input{width:20px;height:20px}.ss-error{font-size:12px;padding:9px;border-radius:8px;background:#f4433622;border:1px solid #f4433655}.ss-view{position:fixed;z-index:21000;right:20px;bottom:80px;left:auto;top:auto;width:min(720px,calc(100vw - 40px));height:min(460px,calc(100vh - 120px));display:none;flex-direction:column;background:#000;border:1px solid #fff3;border-radius:12px;overflow:hidden;box-shadow:0 20px 70px #000b}.ss-view.show{display:flex}.ss-vh{display:flex;align-items:center;gap:10px;padding:9px 12px;background:var(--panel,#20242b);color:var(--text,#fff);flex:none}.ss-vh b{flex:1}.ss-video{display:block;width:100%;height:100%;min-height:0;object-fit:contain;background:#000}.ss-wait{flex:1;display:flex;align-items:center;justify-content:center;color:#fff;text-align:center;padding:20px}.ss-controls{display:flex;gap:8px;padding:9px;background:var(--panel,#20242b);flex:none}.ss-controls button{flex:1}.ss-full{border:0;background:#fff1;color:inherit;border-radius:7px;padding:6px 9px;cursor:pointer}.ss-reopen{position:fixed;right:18px;bottom:18px;z-index:20500;display:none;padding:10px 15px;border:1px solid #fff2;border-radius:9px;background:var(--panel,#20242b);color:var(--text,#fff);cursor:pointer;box-shadow:0 8px 30px #0007}.ss-reopen.show{display:block}`;document.head.appendChild(css);
const menu=document.createElement('div');menu.className='ss-o';menu.innerHTML=`<div class="ss-box"><div class="ss-h"><b>🖥️ Screen Share</b><button class="ss-x" id="ssmx">×</button></div><div class="ss-b"><div class="ss-f"><label>Quality</label><select class="ss-s" id="ssq">${Q.map(x=>`<option value="${x}">${x}p</option>`).join('')}</select></div><div class="ss-f"><label>FPS</label><select class="ss-s" id="ssf">${F.map(x=>`<option value="${x}">${x} FPS</option>`).join('')}</select></div><label class="ss-toggle"><span>🔊 Share audio</span><input type="checkbox" id="ssa" ${shareAudio?'checked':''}></label><div class="ss-note">Audio is enabled by default. Your browser may restrict system/tab audio.</div><div id="ssaerr"></div><button class="ss-btn" id="ssstart">Start screen share</button></div></div>`;document.body.appendChild(menu);
const prompt=document.createElement('div');prompt.className='ss-o';prompt.innerHTML=`<div class="ss-box"><div class="ss-h"><b>🖥️ Screen share available</b><button class="ss-x" id="sspx">×</button></div><div class="ss-b"><div>Someone is sharing their screen.</div><div class="ss-note">You can close this and reopen the viewer later.</div><button class="ss-btn" id="sswatch">Watch Live</button><button class="ss-btn" id="ssno">Not now</button></div></div>`;document.body.appendChild(prompt);
const reopen=document.createElement('button');reopen.className='ss-reopen';reopen.textContent='🖥️ Open Screen Share';document.body.appendChild(reopen);
const view=document.createElement('div');view.className='ss-view';view.innerHTML=`<div class="ss-vh"><b id="sshost">🖥️ Screen Share</b><span id="ssstate">Connecting…</span><button class="ss-full" id="ssfull">⛶</button><button class="ss-x" id="ssclose">×</button></div><div class="ss-wait" id="sswait">Connecting to live screen…</div><video id="ssvideo" class="ss-video" autoplay playsinline style="display:none"></video><div class="ss-controls" id="sscontrols" style="display:none"><button class="ss-btn" id="ssfreeze">Freeze</button><button class="ss-btn" id="ssstop">Stop</button></div></div>`;document.body.appendChild(view);
const selQ=menu.querySelector('#ssq'),selF=menu.querySelector('#ssf'),audioToggle=menu.querySelector('#ssa'),audioErr=menu.querySelector('#ssaerr'),video=view.querySelector('#ssvideo'),wait=view.querySelector('#sswait'),host=view.querySelector('#sshost'),state=view.querySelector('#ssstate'),controls=view.querySelector('#sscontrols'),freeze=view.querySelector('#ssfreeze');selQ.value=q;selF.value=f;
const open=x=>x.classList.add('show'),close=x=>x.classList.remove('show');
async function api(action,extra={}){const r=await fetch(API,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,channel:channel(),device_id:device(),username:user(),share_id:sid,quality:q,fps:f,audio:shareAudio,...extra})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Screen-share error (${r.status})`);return d}
function loadPeer(){return new Promise((resolve,reject)=>{if(window.Peer)return resolve();const s=document.createElement('script');s.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';s.onload=resolve;s.onerror=()=>reject(Error('Could not load PeerJS.'));document.head.appendChild(s)})}
function attachIncomingCall(c){if(!c)return;try{c.answer(watching?'':undefined)}catch{try{c.answer()}catch{}}c.on('stream',s=>{video.srcObject=s;video.muted=false;video.style.display='block';wait.style.display='none';state.textContent='Live'+(s.getAudioTracks().length?'':' • No audio (host/browser did not provide audio)');video.play().catch(()=>{})});c.on('close',()=>{if(watching&&video.srcObject===null){state.textContent='Disconnected'}});c.on('error',e=>{console.warn('Incoming screen call failed',e);if(watching){state.textContent='Connection failed';wait.textContent='The host connection failed. Waiting for reconnect…'}})}
function makePeer(){return new Promise((resolve,reject)=>{if(peer&&!peer.destroyed&&peer.open)return resolve(peer.id);peer=new Peer({debug:1,config:{iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]}});let done=false;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(t);fn(v)};const t=setTimeout(()=>finish(reject,Error('PeerJS connection timed out.')),20000);peer.on('open',id=>finish(resolve,id));peer.on('error',e=>{console.error('PeerJS:',e);if(!done)finish(reject,e)});peer.on('disconnected',()=>{try{peer.reconnect()}catch{}});peer.on('call',c=>{if(sharing&&stream){try{c.answer(stream)}catch{c.close()}}else if(watching||watchPeerId){attachIncomingCall(c)}else c.close()})})}
async function start(){q=+selQ.value;f=+selF.value;shareAudio=audioToggle.checked;localStorage.setItem('screen_share_quality',q);localStorage.setItem('screen_share_fps',f);localStorage.setItem('screen_share_audio',shareAudio?'1':'0');audioErr.innerHTML='';try{await loadPeer();stream=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:q},height:{ideal:Math.round(q*9/16)},frameRate:{ideal:f,max:f},contentHint:'motion'},audio:shareAudio});if(shareAudio&&!stream.getAudioTracks().length)audioErr.innerHTML='<div class="ss-error">Your browser did not provide screen audio. Screen sharing will continue without audio. Your browser may restrict system/tab audio.</div>';const pid=await makePeer();const r=await api('start',{peer_id:pid,audio:shareAudio&&stream.getAudioTracks().length>0});sid=String(r.shareId||'');if(!sid)throw Error('Could not create screen-share session.');sharing=true;watching=false;viewerHidden=false;open(view);reopen.classList.remove('show');host.textContent='🖥️ You are hosting';state.textContent=stream.getAudioTracks().length?'Live • Audio on':'Live • No audio';controls.style.display='flex';video.srcObject=stream;video.muted=true;video.style.display='block';wait.style.display='none';close(menu);hb=setInterval(()=>{if(sharing)api('heartbeat').catch(()=>{})},5000);stream.getVideoTracks()[0].addEventListener('ended',stop,{once:true})}catch(e){if(stream)stream.getTracks().forEach(x=>x.stop());stream=null;if(peer){try{peer.destroy()}catch{}peer=null}if(e.name!=='NotAllowedError')alert(e.message||'Could not start screen sharing.')}}
async function connectViewer(pid,hn,shareId){watching=true;viewerHidden=false;currentRemoteShareId=String(shareId||'');open(view);reopen.classList.remove('show');host.textContent='🖥️ Screen shared by '+(hn||'User');state.textContent='Connecting…';wait.textContent='Waiting for host to connect…';wait.style.display='flex';video.style.display='none';try{await loadPeer();const myId=await makePeer();watchPeerId=String(myId);await api('join',{peer_id:watchPeerId,share_id:currentRemoteShareId});state.textContent='Waiting for host…'}catch(e){state.textContent='Connection failed';wait.textContent=e.message||'Could not connect.'}}
function connectHostViewers(viewers){if(!sharing||!peer||!stream)return;for(const pid of Array.isArray(viewers)?viewers:[]){if(!pid||hostCalls.has(pid)||pid===peer.id)continue;try{const c=peer.call(pid,stream,{metadata:{type:'screen-share',quality:q,fps:f,audio:stream.getAudioTracks().length>0}});if(!c)continue;hostCalls.set(pid,c);c.on('close',()=>hostCalls.delete(pid));c.on('error',e=>{console.warn('Viewer call failed',pid,e);hostCalls.delete(pid)})}catch(e){console.warn('Viewer call error',e)}}}
async function resetViewer(){watching=false;currentRemoteShareId='';watchPeerId='';try{if(video.srcObject)video.srcObject=null}catch{}video.style.display='none';wait.style.display='flex';state.textContent='';if(peer){try{peer.destroy()}catch{}peer=null}}
async function poll(){try{const r=await fetch(API+'?channel='+encodeURIComponent(channel())+'&_='+Date.now(),{cache:'no-store'}),d=await r.json(),s=d.share;if(!s){if(sharing)return;if(watching||lastLiveKey!==null){await resetViewer()}lastLiveKey=null;close(prompt);close(view);reopen.classList.remove('show');window._ssPrompt=null;return}const liveKey=String(s.id||s.shareId||s.startedAt||s.createdAt||s.peerId||s.deviceId);if(s.deviceId===device()){if(sharing){if(!viewerHidden)open(view);reopen.classList.toggle('show',viewerHidden);state.textContent=frozen?'Frozen':(stream?.getAudioTracks().length?'Live • Audio on':'Live • No audio');connectHostViewers(s.viewerPeers)}}else{if(lastLiveKey!==null&&lastLiveKey!==liveKey){await resetViewer();viewerHidden=false;close(view);reopen.classList.remove('show');window._ssPrompt=null}lastLiveKey=liveKey;if(!watching&&!viewerHidden&&window._ssPrompt!==liveKey){window._ssPrompt=liveKey;open(prompt)}}}catch(e){console.warn('Screen-share poll failed',e)}}
async function fullscreen(){if(document.fullscreenElement){try{await document.exitFullscreen()}catch{}return}try{if(view.requestFullscreen)await view.requestFullscreen()}catch{}}
async function stop(){if(!sharing)return;sharing=false;watching=false;viewerHidden=false;clearInterval(hb);hb=null;for(const c of hostCalls.values()){try{c.close()}catch{}}hostCalls.clear();if(stream){stream.getTracks().forEach(x=>x.stop());stream=null}try{await api('stop')}catch{}sid='';if(peer){try{peer.destroy()}catch{}peer=null}close(view);reopen.classList.remove('show')}
btn.onclick=e=>{e.preventDefault();e.stopPropagation();open(menu)};menu.querySelector('#ssmx').onclick=()=>close(menu);audioToggle.onchange=()=>{shareAudio=audioToggle.checked;localStorage.setItem('screen_share_audio',shareAudio?'1':'0')};prompt.querySelector('#sspx').onclick=()=>{close(prompt);reopen.classList.add('show')};prompt.querySelector('#ssno').onclick=()=>{close(prompt);reopen.classList.add('show')};reopen.onclick=()=>{if(watching){viewerHidden=false;open(view);return}fetch(API+'?channel='+encodeURIComponent(channel())+'&_='+Date.now(),{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.share?.peerId)connectViewer(d.share.peerId,d.share.host,d.share.id);else reopen.classList.remove('show')}).catch(()=>{})};menu.querySelector('#ssstart').onclick=start;prompt.querySelector('#sswatch').onclick=async()=>{try{const r=await fetch(API+'?channel='+encodeURIComponent(channel())+'&_='+Date.now(),{cache:'no-store'}),d=await r.json();if(d.share?.peerId){close(prompt);await connectViewer(d.share.peerId,d.share.host,d.share.id)}}catch{}};view.querySelector('#ssfull').onclick=fullscreen;view.querySelector('#ssclose').onclick=()=>{viewerHidden=true;close(view);reopen.classList.add('show')};freeze.onclick=async()=>{if(!sharing)return;frozen=!frozen;freeze.textContent=frozen?'Resume':'Freeze';state.textContent=frozen?'Frozen':'Live';if(stream)stream.getVideoTracks().forEach(t=>t.enabled=!frozen);try{await api('freeze',{frozen})}catch{}};view.querySelector('#ssstop').onclick=stop;setInterval(poll,1000);poll();
})();