-- Screen sharing storage for the chat app.
-- Run this once in Supabase SQL Editor.

create table if not exists public.screen_share_sessions (
    id text primary key,
    host_device_id text not null,
    host_username text not null,
    started_at timestamptz not null default now(),
    heartbeat_at timestamptz not null default now()
);

create table if not exists public.screen_share_signals (
    id bigint generated by default as identity primary key,
    session_id text not null references public.screen_share_sessions(id) on delete cascade,
    sender_device_id text not null,
    target_device_id text not null,
    type text not null,
    payload jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists screen_share_signals_target_idx
    on public.screen_share_signals(session_id, target_device_id, id);

alter table public.screen_share_sessions enable row level security;
alter table public.screen_share_signals enable row level security;

-- The Vercel API route is the gatekeeper. These policies allow the route's
-- Supabase publishable key to use the tables, just like the existing messages API.
drop policy if exists screen_share_sessions_all on public.screen_share_sessions;
create policy screen_share_sessions_all
    on public.screen_share_sessions
    for all
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists screen_share_signals_all on public.screen_share_signals;
create policy screen_share_signals_all
    on public.screen_share_signals
    for all
    to anon, authenticated
    using (true)
    with check (true);


-- Stream settings/description. Run these if the table already existed.
alter table public.screen_share_sessions add column if not exists quality integer not null default 450;
alter table public.screen_share_sessions add column if not exists fps integer not null default 15;
alter table public.screen_share_sessions add column if not exists width integer not null default 800;
alter table public.screen_share_sessions add column if not exists height integer not null default 450;
alter table public.screen_share_sessions add column if not exists surface text not null default 'Screen / display';
alter table public.screen_share_sessions add column if not exists source_label text not null default 'Shared display';
