/* PeerJS WebRTC screen share. Chat/API only carries the Peer ID; video frames never go through chat. */
(()=>{
"use strict";
const button=document.getElementById("screenShareHeaderBtn");if(!button)return;
const API="/api/screen-share",QUALITY=[150,300,450,600,750],FPS=[5,10,15,20,25,30];
let quality=+localStorage.getItem("screen_share_quality")||450,fps=+localStorage.getItem("screen_share_fps")||25;
if(!QUALITY.includes(quality))quality=450;if(!FPS.includes(fps))fps=25;
let peer=null,stream=null,call=null,shareId="",sharing=false,watching=false,frozen=false,heartbeat=null,peerReady=false,dummyStream=null;
const id=()=>{let x=localStorage.getItem("chat_device_id");if(!x){x=crypto.randomUUID?crypto.randomUUID():"ss-"+Date.now()+Math.random();localStorage.setItem("chat_device_id",x)}return x};
const name=()=>window.settings?.username||localStorage.getItem("chat_username")||"User",channel=()=>window.CHANNEL||"general";
const css=document.createElement("style");css.textContent=`.ss-o{position:fixed;inset:0;z-index:20000;display:none;align-items:flex-start;justify-content:flex-end;padding:70px 18px;background:#0004}.ss-o.show{display:flex}.ss-box{width:min(400px,calc(100vw - 36px));background:var(--panel,#20242b);color:var(--text,#fff);border:1px solid #fff2;border-radius:12px;box-shadow:0 20px 60px #0009;overflow:hidden}.ss-h{display:flex;align-items:center;gap:10px;padding:13px 15px;border-bottom:1px solid #fff2}.ss-h b{flex:1}.ss-x{border:0;background:none;color:inherit;font-size:22px;cursor:pointer}.ss-b{display:grid;gap:12px;padding:15px}.ss-f{display:grid;gap:6px}.ss-f label,.ss-note{font-size:12px;opacity:.7}.ss-s,.ss-btn{width:100%;box-sizing:border-box;padding:10px;border-radius:8px;border:1px solid #fff2;background:#fff1;color:inherit}.ss-btn{cursor:pointer;font-weight:600}.ss-view{position:fixed;inset:0;z-index:21000;display:none;background:#000}.ss-view.show{display:flex;flex-direction:column}.ss-vh{display:flex;align-items:center;gap:10px;padding:9px 12px;background:var(--panel,#20242b);color:var(--text,#fff);flex:none}.ss-vh b{flex:1}.ss-img{display:block;width:100%;height:100%;object-fit:contain;background:#000}.ss-wait{flex:1;display:flex;align-items:center;justify-content:center;color:#fff}.ss-controls{display:flex;gap:8px;padding:9px;background:var(--panel,#20242b);flex:none}.ss-controls button{flex:1}.ss-full{border:0;background:#fff1;color:inherit;border-radius:7px;padding:6px 9px;cursor:pointer}.ss-native-full{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;right:0!important;bottom:0!important;border-radius:0!important}`;document.head.appendChild(css);
const menu=document.createElement("div");menu.className="ss-o";menu.innerHTML=`<div class="ss-box"><div class="ss-h"><b>🖥️ Screen Share</b><button class="ss-x" id="ssmx">×</button></div><div class="ss-b"><div class="ss-f"><label>Quality</label><select class="ss-s" id="ssq">${QUALITY.map(x=>`<option value="${x}">${x}p</option>`).join("")}</select></div><div class="ss-f"><label>FPS</label><select class="ss-s" id="ssf">${FPS.map(x=>`<option value="${x}">${x} FPS</option>`).join("")}</select></div><div class="ss-note">Live video uses PeerJS WebRTC. Maximum 750p / 30 FPS.</div><button class="ss-btn" id="ssstart">Start screen share</button></div></div>`;document.body.appendChild(menu);
const prompt=document.createElement("div");prompt.className="ss-o";prompt.innerHTML=`<div class="ss-box"><div class="ss-h"><b>🖥️ Screen share available</b><button class="ss-x" id="sspx">×</button></div><div class="ss-b"><div>Someone is sharing their screen.</div><div class="ss-note">Watch Live connects directly to the host.</div><button class="ss-btn" id="sswatch">Watch live</button><button class="ss-btn" id="ssno">Not now</button></div></div>`;document.body.appendChild(prompt);
const view=document.createElement("div");view.className="ss-view";view.innerHTML=`<div class="ss-vh"><b id="sshost">🖥️ Screen Share</b><span id="ssstate">Connecting…</span><button class="ss-full" id="ssfull">⛶</button><button class="ss-x" id="ssclose">×</button></div><div class="ss-wait" id="sswait">Connecting to live screen…</div><video id="ssvideo" class="ss-img" autoplay playsinline muted style="display:none"></video><div class="ss-controls" id="sscontrols" style="display:none"><button class="ss-btn" id="ssfreeze">Freeze</button><button class="ss-btn" id="ssstop">Stop</button></div></div>`;document.body.appendChild(view);
const q=menu.querySelector("#ssq"),f=menu.querySelector("#ssf"),video=view.querySelector("#ssvideo"),wait=view.querySelector("#sswait"),host=view.querySelector("#sshost"),state=view.querySelector("#ssstate"),controls=view.querySelector("#sscontrols"),freeze=view.querySelector("#ssfreeze");q.value=quality;f.value=fps;
const open=x=>x.classList.add("show"),close=x=>x.classList.remove("show");
async function api(action,extra={}){const r=await fetch(API,{method:"POST",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,channel:channel(),device_id:id(),username:name(),share_id:shareId,quality,fps,...extra})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Screen share error (${r.status})`);return d}
function loadPeerJS(){return new Promise((resolve,reject)=>{if(window.Peer)return resolve();const s=document.createElement("script");s.src="https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js";s.onload=()=>window.Peer?resolve():reject(Error("PeerJS failed to load."));s.onerror=()=>reject(Error("Could not load PeerJS."));document.head.appendChild(s)})}
function makePeer(){return new Promise((resolve,reject)=>{if(peer){try{peer.destroy()}catch{}peer=null}peerReady=false;peer=new window.Peer();const timer=setTimeout(()=>{try{peer.destroy()}catch{}reject(Error("PeerJS connection timed out."))},15000);peer.on("open",pid=>{clearTimeout(timer);peerReady=true;resolve(pid)});peer.on("error",e=>{clearTimeout(timer);reject(e)});peer.on("call",incoming=>{if(sharing&&stream){incoming.answer(stream);incoming.on("close",()=>{});incoming.on("error",()=>{});}else{try{incoming.close()}catch{}}})})}
async function start(){quality=+q.value;fps=+f.value;localStorage.setItem("screen_share_quality",quality);localStorage.setItem("screen_share_fps",fps);try{await loadPeerJS();stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:fps,max:fps},width:{ideal:quality}},audio:false});const pid=await makePeer();const r=await api("start",{peer_id:pid});shareId=String(r.shareId||"");if(!shareId)throw Error("Could not create screen-share session.");sharing=true;watching=true;open(view);host.textContent="🖥️ You are hosting";state.textContent="Live";controls.style.display="flex";video.srcObject=stream;video.muted=true;video.style.display="block";wait.style.display="none";close(menu);heartbeat=setInterval(()=>{if(sharing)api("heartbeat").catch(()=>{})},5000);stream.getVideoTracks()[0].addEventListener("ended",stop,{once:true})}catch(e){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(peer){try{peer.destroy()}catch{}peer=null}if(e.name!=="NotAllowedError")alert(e.message||"Could not start screen sharing.")}}
function createDummyVideo(){const c=document.createElement("canvas");c.width=2;c.height=2;const x=c.getContext("2d");x.fillRect(0,0,2,2);return c.captureStream(1)}
async function watch(peerId,hostName){watching=true;open(view);host.textContent="🖥️ Screen shared by "+(hostName||"User");state.textContent="Connecting…";wait.textContent="Connecting to live screen…";wait.style.display="flex";video.style.display="none";try{await loadPeerJS();if(!peerReady)await makePeer();if(call){try{call.close()}catch{}call=null}dummyStream=createDummyVideo();call=peer.call(peerId,dummyStream);if(!call)throw Error("Could not create PeerJS call.");call.on("stream",remote=>{video.srcObject=remote;video.muted=false;video.play().catch(()=>{});wait.style.display="none";video.style.display="block";state.textContent="Live"});call.on("close",()=>{state.textContent="Stopped";video.srcObject=null;wait.textContent="The screen share ended.";wait.style.display="flex";video.style.display="none"});call.on("error",e=>{state.textContent="Connection failed";wait.textContent=e?.message||"Could not connect to the host."})}catch(e){state.textContent="Connection failed";wait.textContent=e.message||"Could not connect."}}
async function poll(){try{const r=await fetch(API+"?channel="+encodeURIComponent(channel())+"&_="+Date.now(),{cache:"no-store"}),d=await r.json(),s=d.share;if(!s){if(!sharing){watching=false;close(view)}return}if(s.deviceId===id()){if(sharing){open(view);host.textContent="🖥️ You are hosting";state.textContent=frozen?"Frozen":"Live";controls.style.display="flex"}}else if(!watching){const key=String(s.id||s.deviceId);if(window._ssPrompt!==key){window._ssPrompt=key;open(prompt)}}}catch{}}
async function fullscreen(){if(document.fullscreenElement){try{await document.exitFullscreen()}catch{}return}try{if(view.requestFullscreen)await view.requestFullscreen();else view.classList.add("ss-native-full")}catch{view.classList.add("ss-native-full")}}
button.onclick=e=>{e.preventDefault();e.stopPropagation();open(menu)};menu.querySelector("#ssmx").onclick=()=>close(menu);prompt.querySelector("#sspx").onclick=()=>close(prompt);prompt.querySelector("#ssno").onclick=()=>close(prompt);prompt.querySelector("#sswatch").onclick=async()=>{try{const r=await fetch(API+"?channel="+encodeURIComponent(channel())+"&_="+Date.now(),{cache:"no-store"}),d=await r.json();if(d.share&&d.share.peerId){close(prompt);await watch(d.share.peerId,d.share.host)}else{wait.textContent="No active screen share."}}catch(e){alert(e.message||"Could not find the screen share.")}};menu.querySelector("#ssstart").onclick=start;view.querySelector("#ssfull").onclick=fullscreen;view.addEventListener("dblclick",fullscreen);view.querySelector("#ssclose").onclick=()=>{if(!sharing){watching=false;if(call){try{call.close()}catch{}call=null}if(dummyStream)dummyStream.getTracks().forEach(t=>t.stop());close(view)}};freeze.onclick=async()=>{if(!sharing)return;frozen=!frozen;freeze.textContent=frozen?"Resume":"Freeze";state.textContent=frozen?"Frozen":"Live";if(stream)stream.getVideoTracks().forEach(t=>t.enabled=!frozen);try{await api("freeze",{frozen})}catch{}};view.querySelector("#ssstop").onclick=stop;
async function stop(){if(!sharing)return;sharing=false;watching=false;clearInterval(heartbeat);heartbeat=null;if(call){try{call.close()}catch{}call=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(dummyStream){dummyStream.getTracks().forEach(t=>t.stop());dummyStream=null}try{await api("stop")}catch{}shareId="";close(view);if(peer){try{peer.destroy()}catch{}peer=null}peerReady=false}
setInterval(poll,1000);poll();
})();