(()=>{'use strict';
const G=[
 ['ttt3','❌⭕','Tic-Tac-Toe 3x3','Play against a bot'],['ttt4','❌⭕','Tic-Tac-Toe 4x4','Play against a bot'],['ttt5','❌⭕','Tic-Tac-Toe 5x5','Play against a bot'],['ttt6','❌⭕','Tic-Tac-Toe 6x6','Play against a bot'],
 ['hangman','🔤','Hangman','Guess the bot word'],['battleship','🚢','Battleship','Battle the bot fleet'],['memory','🧠','Memory Match','Beat the bot'],['quickdraw','🏁','Quick Draw','Beat the bot reaction'],['coinflip','🪙','Coin Flip','Play against the bot'],['numberguess','🔢','Number Guess','Beat the bot'],['target','🎯','Target Click','Beat the bot score'],['reaction','⚡','Reaction Time','Beat the bot time'],['type','⌨️','Type Sentence','Beat the bot time'],['boss','👹','Boss Battle','Fight with a bot ally'],['trivia','🧠','Trivia Quiz','Beat the bot score'],['wordscramble','🔤','Word Scramble','Beat the bot'],['mathrace','➗','Math Race','Beat the bot'],['rpstournament','🏆','RPS vs Bot','Rock Paper Scissors vs bot']
];
const css=`.sp2-card{border:1px solid #30343c;background:#181b21;color:#fff;border-radius:14px;padding:15px;text-align:left;cursor:pointer}.sp2-card:hover{border-color:#7564ff;transform:translateY(-2px)}.sp2-tag{display:inline-block;margin-top:8px;font-size:11px;color:#8ee6b2}.sp2-overlay{position:fixed;inset:0;z-index:40000;background:rgba(0,0,0,.76);display:flex;align-items:center;justify-content:center;padding:18px}.sp2-panel{width:min(760px,96vw);max-height:92vh;overflow:auto;background:#15181e;border:1px solid #343a44;border-radius:18px;color:#fff}.sp2-head{display:flex;justify-content:space-between;padding:16px;border-bottom:1px solid #30343c}.sp2-body{padding:18px}.sp2-btn{border:0;border-radius:9px;padding:10px 14px;background:#6654e8;color:#fff;cursor:pointer}.sp2-status{text-align:center;color:#aab2bd;margin-bottom:14px}.sp2-board{display:grid;gap:6px;justify-content:center}.sp2-ttt button{width:64px;height:64px;font-size:28px}.sp2-ttt{grid-template-columns:repeat(var(--n),64px)}.sp2-input{display:block;margin:12px auto;padding:10px;border-radius:9px;border:1px solid #414854;background:#0f1217;color:#fff}.sp2-actions{display:flex;justify-content:center;gap:8px;margin-top:14px}.sp2-score{text-align:center;color:#aab2bd;margin:10px}.sp2-grid{grid-template-columns:repeat(10,32px)}.sp2-grid button{width:32px;height:32px;border:0;border-radius:4px;background:#303640;color:#fff}.sp2-choices{display:flex;gap:8px;justify-content:center;flex-wrap:wrap}.sp2-choice{padding:12px 16px;border-radius:10px;border:1px solid #454b55;background:#20242b;color:#fff;cursor:pointer}`;
function addCss(){if(document.getElementById('sp2css'))return;let s=document.createElement('style');s.id='sp2css';s.textContent=css;document.head.appendChild(s)}
const games={};
function open(type,title){let o=document.createElement('div');o.className='sp2-overlay';o.innerHTML=`<div class="sp2-panel"><div class="sp2-head"><b>${title} · 🤖 Bot</b><button class="sp2-btn" id="sp2close">Close</button></div><div class="sp2-body"><div id="sp2status" class="sp2-status">Loading…</div><div id="sp2board"></div><div class="sp2-actions"><button class="sp2-btn" id="sp2restart">Restart</button></div></div></div>`;document.body.appendChild(o);o.querySelector('#sp2close').onclick=()=>o.remove();o.querySelector('#sp2restart').onclick=()=>{o.remove();open(type,title)};games[type]?.(o.querySelector('#sp2board'),o.querySelector('#sp2status'),o)}
function simpleTime(b,s,label){let start=0,btn=document.createElement('button');btn.className='sp2-btn';btn.textContent=label;b.appendChild(btn);btn.onclick=()=>{btn.disabled=true;start=performance.now();let wait=500+Math.random()*1400;setTimeout(()=>{let player=Math.round(performance.now()-start),bot=Math.round(450+Math.random()*1200);s.textContent=`You: ${player} ms · Bot: ${bot} ms · ${player<bot?'You win!':'Bot wins!'}`},wait)};s.textContent='Ready.'}
games.quickdraw=(b,s)=>simpleTime(b,s,'DRAW! Click');games.reaction=(b,s)=>simpleTime(b,s,'Start reaction test');games.target=(b,s)=>simpleTime(b,s,'Start target test');
games.type=(b,s)=>{let text='The quick brown fox jumps over the lazy dog.';b.innerHTML=`<div style="text-align:center;margin-bottom:10px">${text}</div><input class="sp2-input" placeholder="Type it exactly"><button class="sp2-btn">Submit</button>`;let i=b.querySelector('input'),q=b.querySelector('button'),start=0;i.oninput=()=>{if(!start)start=performance.now()};q.onclick=()=>{if(i.value!==text)return;let you=(performance.now()-start)/1000,bot=1+Math.random()*2;s.textContent=`You: ${you.toFixed(2)}s · Bot: ${bot.toFixed(2)}s · ${you<bot?'You win!':'Bot wins!'}`}};
games.coinflip=(b,s)=>{let you=0,bot=0;b.innerHTML='<div class="sp2-choices"><button class="sp2-choice">Heads</button><button class="sp2-choice">Tails</button></div>';b.querySelectorAll('button').forEach(q=>q.onclick=()=>{let p=q.textContent.toLowerCase(),r=Math.random()<.5?'heads':'tails',br=Math.random()<.5?'heads':'tails';if(p===r)you++;if(br===r)bot++;s.textContent=`You ${you} · Bot ${bot} · Coin: ${r}`;if(you>=5||bot>=5)s.textContent+=you>=5?' · You win!':' · Bot wins!'})};
games.numberguess=(b,s)=>{let secret=1+Math.floor(Math.random()*100),tries=0;b.innerHTML='<input class="sp2-input" type="number" placeholder="1-100"><button class="sp2-btn">Guess</button>';let i=b.querySelector('input'),q=b.querySelector('button');q.onclick=()=>{let n=+i.value;if(n<1||n>100)return;tries++;if(n===secret){s.textContent=`You win in ${tries} guesses!`;q.disabled=true}else s.textContent=n<secret?'Higher!':'Lower!'}};
games.hangman=(b,s)=>{let words=['APPLE','HOUSE','PLANET','RIVER','DRAGON','FOREST','COMPUTER','GARDEN'],word=words[Math.floor(Math.random()*words.length)],used=new Set(),tries=6;function draw(){b.innerHTML=`<div style="font-size:28px;text-align:center;letter-spacing:8px">${[...word].map(c=>used.has(c)?c:'_').join(' ')}</div><div class="sp2-choices" id="letters"></div>`;for(let c of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'){let q=document.createElement('button');q.className='sp2-choice';q.textContent=c;q.disabled=used.has(c)||tries<=0;q.onclick=()=>{used.add(c);if(!word.includes(c))tries--;if([...word].every(x=>used.has(x))){s.textContent='You win!';return}if(tries<=0){s.textContent=`Bot wins — word was ${word}`;return}draw();s.textContent=`Attempts left: ${tries}`}}}draw();s.textContent='Guess the bot word.'};
function ttt(b,s,n){let a=Array(n*n).fill(''),done=false;b.innerHTML=`<div class="sp2-board sp2-ttt" style="--n:${n}"></div>`;let g=b.firstChild;function win(x){for(let r=0;r<n;r++)for(let c=0;c<n;c++)for(let [dr,dc] of [[1,0],[0,1],[1,1],[1,-1]]){let ok=true;for(let k=0;k<n;k++){let rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=n||cc<0||cc>=n||a[rr*n+cc]!==x){ok=false;break}}if(ok)return true}return false}function draw(){g.innerHTML='';a.forEach((v,i)=>{let q=document.createElement('button');q.textContent=v;q.disabled=!!v||done;q.onclick=()=>{a[i]='X';if(win('X')){done=true;s.textContent='You win!';draw();return}if(!a.includes('')){done=true;s.textContent='Draw!';draw();return}draw();setTimeout(bot,250)};g.appendChild(q)})}function bot(){if(done)return;let f=a.map((v,i)=>v?null:i).filter(x=>x!==null);if(!f.length)return;let i=f[Math.floor(Math.random()*f.length)];a[i]='O';if(win('O')){done=true;s.textContent='Bot wins!'}else if(!a.includes('')){done=true;s.textContent='Draw!'}draw()}draw();s.textContent='You are X · Bot is O'}
for(let n=3;n<=6;n++)games['ttt'+n]=((nn)=>(b,s)=>ttt(b,s,nn))(n);
games.battleship=(b,s)=>{let mines=new Set();while(mines.size<15)mines.add(Math.floor(Math.random()*100));let hit=0;b.innerHTML='<div class="sp2-board sp2-grid"></div>';let g=b.firstChild;for(let i=0;i<100;i++){let q=document.createElement('button');q.onclick=()=>{if(q.disabled)return;q.disabled=true;if(mines.has(i)){q.textContent='💥';hit++;s.textContent=`Hits: ${hit}/15`;if(hit===15)s.textContent='You destroyed the bot fleet! 🎉'}else{q.textContent='•';s.textContent='Miss — try another coordinate.'}};g.appendChild(q)}};
games.memory=(b,s)=>{let vals=['🍎','🍊','🍋','🍇','🍉','🍓','🍒','🥝'],cards=[...vals,...vals].sort(()=>Math.random()-.5),open=[],matched=0,g=document.createElement('div');g.className='sp2-board';g.style.gridTemplateColumns='repeat(4,60px)';b.appendChild(g);function draw(){g.innerHTML='';cards.forEach((v,i)=>{let q=document.createElement('button');q.className='sp2-choice';q.style.width='60px';q.style.height='60px';q.textContent=open.includes(i)?v:'?';q.onclick=()=>{if(open.includes(i)||open.length>=2)return;open.push(i);draw();if(open.length===2)setTimeout(()=>{if(cards[open[0]]===cards[open[1]])matched++;open=[];draw();s.textContent=`Pairs: ${matched}/${vals.length}`;if(matched===vals.length)s.textContent='You win!'},450)}})}draw();s.textContent='Match all pairs.'};
games.trivia=(b,s)=>{let qs=[['Capital of France?',['Paris','Rome','Oslo'],0],['2+2?',['3','4','5'],1],['Largest planet?',['Mars','Earth','Jupiter'],2]],i=0,score=0;function draw(){if(i>=qs.length){let bot=Math.floor(Math.random()*2)+1;s.textContent=`You: ${score} · Bot: ${bot} · ${score>bot?'You win!':score===bot?'Draw!':'Bot wins!'}`;return}let [q,o,a]=qs[i];b.innerHTML=`<div style="text-align:center;margin:12px">${q}</div><div class="sp2-choices"></div>`;o.forEach((x,j)=>{let z=document.createElement('button');z.className='sp2-choice';z.textContent=x;z.onclick=()=>{if(j===a)score++;i++;draw()}})}draw()};
games.wordscramble=(b,s)=>{let w=['APPLE','PLANET','DRAGON','RIVER'][Math.floor(Math.random()*4)],scr=[...w].sort(()=>Math.random()-.5).join('');b.innerHTML=`<div style="text-align:center;font-size:30px">${scr}</div><input class="sp2-input" placeholder="Answer"><button class="sp2-btn">Submit</button>`;let i=b.querySelector('input');b.querySelector('button').onclick=()=>s.textContent=i.value.toUpperCase()===w?'You win!':`Bot wins — word was ${w}`};
games.mathrace=(b,s)=>{let a=Math.floor(Math.random()*20)+1,c=Math.floor(Math.random()*20)+1,ans=a+c;b.innerHTML=`<div style="text-align:center;font-size:30px">${a} + ${c} = ?</div><input class="sp2-input" type="number"><button class="sp2-btn">Submit</button>`;let i=b.querySelector('input');b.querySelector('button').onclick=()=>s.textContent=+i.value===ans?'You win!':'Bot wins!'};
games.rpstournament=(b,s)=>{b.innerHTML='<div class="sp2-choices"><button class="sp2-choice">✊ Rock</button><button class="sp2-choice">✋ Paper</button><button class="sp2-choice">✌ Scissors</button></div>';b.querySelectorAll('button').forEach((q,i)=>q.onclick=()=>{let bot=Math.floor(Math.random()*3);s.textContent=i===bot?'Draw!':((i===0&&bot===2)||(i===1&&bot===0)||(i===2&&bot===1)?'You win!':'Bot wins!')})};
games.boss=(b,s)=>{let hp=100,bot=0;b.innerHTML='<button class="sp2-btn">⚔️ Attack</button>';b.firstChild.onclick=()=>{hp-=10+Math.floor(Math.random()*11);bot+=5+Math.floor(Math.random()*8);s.textContent=hp<=0?'Boss defeated! 🎉':`Boss HP: ${hp} · Bot damage: ${bot}`}};
function init(){addCss();let grid=document.querySelector('#gamesOverlay .game-grid');if(!grid)return;grid.innerHTML='';let label=document.createElement('div');label.textContent='SINGLE PLAYER · BOTS';label.style.cssText='grid-column:1/-1;color:#8f98a5;font-size:11px;font-weight:900;letter-spacing:.12em;padding:4px';grid.appendChild(label);G.forEach(([type,icon,name,desc])=>{let q=document.createElement('button');q.className='sp2-card';q.innerHTML=`<strong style="font-size:16px">${icon} ${name}</strong><span style="display:block;color:#9da5b0;font-size:12px;margin-top:5px">${desc}</span><span class="sp2-tag">1 player · bot</span>`;q.onclick=()=>open(type,name);grid.appendChild(q)});let p=document.querySelector('#gamesOverlay .panel-body>p');if(p)p.textContent='Multiplayer games and lobbies have been removed. Every game is local to your device and uses a bot.'}
document.addEventListener('DOMContentLoaded',init);new MutationObserver(init).observe(document.documentElement,{childList:true,subtree:true});setTimeout(init,300);
})();