(()=>{
'use strict';
if(window.ChatMP)return;
const PREFIX='__CHAT_GAME_STATE__:';
const API='/api/messages';
const mods=window.ChatMultiplayerGames={};
const device=()=>localStorage.getItem('chat_device_id')||'';
const name=()=>localStorage.getItem('chat_username')||'Player';
function register(game){mods[game.id]=game}
async function read(){const r=await fetch(API+'?channel=general&mp='+Date.now(),{cache:'no-store'});const j=await r.json();return (j.messages||[]).map(m=>{if(typeof m.message!=='string'||!m.message.startsWith(PREFIX))return null;try{return JSON.parse(m.message.slice(PREFIX.length))}catch{return null}}).filter(Boolean).filter(g=>g&&g.id)}
async function publish(g){g.version=(g.version||0)+1;g.updatedAt=Date.now();const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game_server:true,channel:'general',device_id:device(),message:PREFIX+JSON.stringify(g)})});if(!r.ok)throw new Error('Game state could not be saved');return r.json()}
function id(){return 'mp_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9)}
function openShell(g,host){const root=document.getElementById('gamesV3');if(!root)return;const body=root.querySelector('#g3body'),title=root.querySelector('#g3title');root.classList.add('on');title.textContent=(mods[g.gameType]?.icon||'🎮')+' '+(mods[g.gameType]?.name||g.gameType);body.innerHTML='<div class="g3-play"><div id="mpGame" class="g3-content"></div></div>';const el=body.querySelector('#mpGame');const api={game:g,me:device(),isHost:host===device(),players:g.players||[],publish,refresh:async()=>{const all=await read();const x=all.find(v=>v.id===g.id);if(x){g=x;api.game=x;api.players=x.players||[];mods[x.gameType]?.render?.(el,api)}},leave:async()=>{try{await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game_server:true,game_action:'leave',game_id:g.id,channel:'general',device_id:device()})})}finally{if(window.__mpCleanup)window.__mpCleanup();root.classList.remove('on')}}};mods[g.gameType]?.render?.(el,api);api.timer=setInterval(api.refresh,75);window.__mpCleanup=()=>clearInterval(api.timer)}
async function create(type,settings={}){const m=mods[type];if(!m)return alert('Game is not available yet.');const g={id:id(),gameType:type,status:'lobby',hostDeviceId:device(),players:[{deviceId:device(),username:name()}],minPlayers:m.minPlayers||2,maxPlayers:m.maxPlayers||4,settings:{...settings},data:{},version:0,createdAt:Date.now()};await publish(g);openShell(g,device())}
async function join(g){if(!g||g.status!=='lobby'||(g.players||[]).some(p=>p.deviceId===device())||(g.players||[]).length>=g.maxPlayers)return;g.players=[...(g.players||[]),{deviceId:device(),username:name()}];await publish(g);openShell(g,g.hostDeviceId)}
async function lobby(type){const all=await read();return all.filter(g=>g.gameType===type&&g.status==='lobby'&&!((g.players||[]).some(p=>p.deviceId===device())))}
async function show(type){const m=mods[type];if(!m)return;const all=await lobby(type);if(!all.length)return create(type);const root=document.getElementById('gamesV3'),body=root.querySelector('#g3body'),title=root.querySelector('#g3title');root.classList.add('on');title.textContent=(m.icon||'🎮')+' '+m.name;body.innerHTML='<div class="g3-play"><div class="g3-content"><h3>Join a game</h3><p>Live lobby — updates are checked every 75ms.</p><div id="mpLobby"></div><button class="g3-btn" id="mpCreate">＋ Create new game</button></div></div>';const out=body.querySelector('#mpLobby');out.innerHTML=all.map(g=>`<button class="g3-card" data-j="${g.id}"><span class="g3-icon">${m.icon||'🎮'}</span><b>${g.players?.length||0}/${g.maxPlayers} players</b><small>${(g.players||[]).map(p=>String(p.username||'Player')).join(', ')}</small></button>`).join('');out.querySelectorAll('[data-j]').forEach(b=>b.onclick=()=>{const g=all.find(x=>x.id===b.dataset.j);join(g)});body.querySelector('#mpCreate').onclick=()=>create(type)}
window.ChatMP={register,create,join,show,read,openShell,mods};
// Capture the V3 card click so multiplayer cards always use the new modular files.
document.addEventListener('click',e=>{const b=e.target.closest?.('.g3-card[data-id]');if(!b||!window.ChatMP?.mods[b.dataset.id])return;e.preventDefault();e.stopImmediatePropagation();window.ChatMP.show(b.dataset.id)},true);
})();